<div style="font-size: 36px;">
COMS W4111 -- Introduction to Databases, Fall 2025<br>Lecture 6 Examples
</div>

# Initialize Environment

In [1]:
%load_ext sql

In [5]:
db_url = "mysql+pymysql://root:dbuserdbuser@localhost"

In [6]:
# This is a hack to fix a version problem/incompatibility  with some of the packages and magics.
#
%config SqlMagic.style = '_DEPRECATED_DEFAULT'

In [7]:
%sql $db_url

In [8]:
import pandas

In [9]:
from sqlalchemy import create_engine

In [10]:
engine = create_engine(db_url)

In [11]:
import pymysql

# Functions

## Summary

1. Date and Time
    1. Date and time from string
    2. Quarter, Month, Day of Month, ...
    3. Date diff
    4. Makedate
    5. str_to_date
    6. subtimes
2. IF, IFNULL
3. Type conversation
4. String: Length, Position/Locate/Replace, PAD, Trim

## Date and Time

Manipulating time is common in database applications.

MySQL, like most databases, has powerful [date and time processing functions.](https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html)

### Watching Lectures

In [12]:
stats_file = "session-HeatMap_2025-09-13--2025-10-13_9421bb02-ef10-4150-90e0-b3720120101c.csv"

In [13]:
stats_df = pandas.read_csv(stats_file)
stats_df

,Timestamp,Start Position,Minutes Delivered,UserName,User ID,Name,Email
0,10/10/2025 2:24:21 PM,0.000000,0.0188,CVNCanvas\si2471,9c5f4f3d-e997-4b11-84e2-b1c5015b1c8c,Severin Ihnat,si2471@columbia.edu
1,10/10/2025 2:24:38 PM,0.000000,0.1921,CVNCanvas\si2471,9c5f4f3d-e997-4b11-84e2-b1c5015b1c8c,Severin Ihnat,si2471@columbia.edu
2,10/10/2025 2:24:38 PM,11.556562,0.2125,CVNCanvas\si2471,9c5f4f3d-e997-4b11-84e2-b1c5015b1c8c,Severin Ihnat,si2471@columbia.edu
3,10/10/2025 2:25:48 PM,11.556562,2.1763,CVNCanvas\si2471,9c5f4f3d-e997-4b11-84e2-b1c5015b1c8c,Severin Ihnat,si2471@columbia.edu
4,10/10/2025 2:27:34 PM,213.363729,3.5425,CVNCanvas\si2471,9c5f4f3d-e997-4b11-84e2-b1c5015b1c8c,Severin Ihnat,si2471@columbia.edu
...,...,...,...,...,...,...,...
491,10/12/2025 10:17:18 AM,236.600168,1.7233,CVNCanvas\dav2136,bc1702bd-70a9-4d25-a102-b1a1010e25ac,Dominick Vaske,dav2136@columbia.edu
492,10/12/2025 10:17:48 AM,359.701977,0.0232,CVNCanvas\dav2136,bc1702bd-70a9-4d25-a102-b1a1010e25ac,Dominick Vaske,dav2136@columbia.edu
493,10/12/2025 10:32:48 AM,370.767161,30.3812,CVNCanvas\dav2136,bc1702bd-70a9-4d25-a102-b1a1010e25ac,Dominick Vaske,dav2136@columbia.edu
494,10/12/2025 10:55:48 AM,2063.400047,46.2985,CVNCanvas\dav2136,bc1702bd-70a9-4d25-a102-b1a1010e25ac,Dominick Vaske,dav2136@columbia.edu
495,10/12/2025 11:15:11 AM,5401.984102,38.4090,CVNCanvas\dav2136,bc1702bd-70a9-4d25-a102-b1a1010e25ac,Dominick Vaske,dav2136@columbia.edu

In [15]:
%sql create schema if not exists f2025_w4111_examples

 * mysql+pymysql://root:***@localhost
1 rows affected.

[]

In [16]:
stats_df.to_sql(
    "Heatmap_2025_10_13",
    schema="f2025_w4111_examples",
    index=False,
    if_exists="replace",
    con=engine
)

496

In [17]:
%sql use f2025_w4111_examples

 * mysql+pymysql://root:***@localhost
0 rows affected.

[]

In [18]:
%sql describe Heatmap_2025_10_13

 * mysql+pymysql://root:***@localhost
7 rows affected.

[('Timestamp', 'text', 'YES', '', None, ''),
 ('Start Position', 'double', 'YES', '', None, ''),
 ('Minutes Delivered', 'double', 'YES', '', None, ''),
 ('UserName', 'text', 'YES', '', None, ''),
 ('User ID', 'text', 'YES', '', None, ''),
 ('Name', 'text', 'YES', '', None, ''),
 ('Email', 'text', 'YES', '', None, '')]

In [19]:
%sql select * from heatmap_2025_10_13 limit 5

 * mysql+pymysql://root:***@localhost
5 rows affected.

[('10/10/2025 2:24:21 PM', 0.0, 0.0188, 'CVNCanvas\\si2471', '9c5f4f3d-e997-4b11-84e2-b1c5015b1c8c', 'Severin Ihnat', 'si2471@columbia.edu'),
 ('10/10/2025 2:24:38 PM', 0.0, 0.1921, 'CVNCanvas\\si2471', '9c5f4f3d-e997-4b11-84e2-b1c5015b1c8c', 'Severin Ihnat', 'si2471@columbia.edu'),
 ('10/10/2025 2:24:38 PM', 11.556562, 0.2125, 'CVNCanvas\\si2471', '9c5f4f3d-e997-4b11-84e2-b1c5015b1c8c', 'Severin Ihnat', 'si2471@columbia.edu'),
 ('10/10/2025 2:25:48 PM', 11.556562, 2.1763, 'CVNCanvas\\si2471', '9c5f4f3d-e997-4b11-84e2-b1c5015b1c8c', 'Severin Ihnat', 'si2471@columbia.edu'),
 ('10/10/2025 2:27:34 PM', 213.363729, 3.5425, 'CVNCanvas\\si2471', '9c5f4f3d-e997-4b11-84e2-b1c5015b1c8c', 'Severin Ihnat', 'si2471@columbia.edu')]

This is in the format:
%m/%d/%Y %h:%i:%s %p

Where:

- %m = month (2-digit)

- %d = day (2-digit)

- %Y = 4-digit year

- %h = hour (1-12)

- %i = minutes

- %s = seconds

- %p = AM or PM

In [20]:
%%sql

SELECT STR_TO_DATE('10/10/2025 2:24:21 PM', '%m/%d/%Y %h:%i:%s %p') AS view_datetime,
       `Start Position`                                             as start_position_seconds,
       sec_to_time(round(Heatmap_2025_10_13.`Start Position`, 0))   as start_position_hms,
       `Minutes Delivered`                                          as minutes_delivered,
       sec_to_time(round(`Minutes Delivered` * 60, 0))              as minutes_delivered_hms,
       substr(UserName, position('\\' in UserName) + 1)             as user_name
from Heatmap_2025_10_13
limit 10;

 * mysql+pymysql://root:***@localhost
10 rows affected.

[(datetime.datetime(2025, 10, 10, 14, 24, 21), 0.0, datetime.timedelta(0), 0.0188, datetime.timedelta(seconds=1), 'si2471'),
 (datetime.datetime(2025, 10, 10, 14, 24, 21), 0.0, datetime.timedelta(0), 0.1921, datetime.timedelta(seconds=12), 'si2471'),
 (datetime.datetime(2025, 10, 10, 14, 24, 21), 11.556562, datetime.timedelta(seconds=12), 0.2125, datetime.timedelta(seconds=13), 'si2471'),
 (datetime.datetime(2025, 10, 10, 14, 24, 21), 11.556562, datetime.timedelta(seconds=12), 2.1763, datetime.timedelta(seconds=131), 'si2471'),
 (datetime.datetime(2025, 10, 10, 14, 24, 21), 213.363729, datetime.timedelta(seconds=213), 3.5425, datetime.timedelta(seconds=213), 'si2471'),
 (datetime.datetime(2025, 10, 10, 14, 24, 21), 466.405459, datetime.timedelta(seconds=466), 0.0174, datetime.timedelta(seconds=1), 'si2471'),
 (datetime.datetime(2025, 10, 10, 14, 24, 21), 5437.900185, datetime.timedelta(seconds=5438), 0.0375, datetime.timedelta(seconds=2), 'nk3214'),
 (datetime.datetime(2025, 10, 10, 14, 24, 21), 5360.700481, datetime.timedelta(seconds=5361), 0.4029, datetime.timedelta(seconds=24), 'nk3214'),
 (datetime.datetime(2025, 10, 10, 14, 24, 21), 5394.847015, datetime.timedelta(seconds=5395), 0.2865, datetime.timedelta(seconds=17), 'nk3214'),
 (datetime.datetime(2025, 10, 10, 14, 24, 21), 0.0, datetime.timedelta(0), 0.013, datetime.timedelta(seconds=1), 'dff9')]

In [24]:
%%sql

with one as (
    SELECT STR_TO_DATE('10/10/2025 2:24:21 PM', '%m/%d/%Y %h:%i:%s %p') AS view_datetime,
       `Start Position`                                             as start_position_seconds,
       sec_to_time(round(Heatmap_2025_10_13.`Start Position`, 0))   as start_position_hms,
       `Minutes Delivered`                                          as minutes_delivered,
       sec_to_time(round(`Minutes Delivered` * 60, 0))              as minutes_delivered_hms,
       substr(UserName, position('\\' in UserName) + 1)             as user_name
from Heatmap_2025_10_13
),
two as (
    select
    sum(minutes_delivered) as total_minutes,
    user_name
from
    one
group by user_name)
select
    user_name,
    total_minutes,
    sec_to_time(total_minutes*60) as total_hms
from two
order by total_minutes desc;

 * mysql+pymysql://root:***@localhost
10 rows affected.

[('shl2183', 133.54059999999998, datetime.timedelta(seconds=8012, microseconds=436000)),
 ('dav2136', 118.78459999999998, datetime.timedelta(seconds=7127, microseconds=76000)),
 ('yy3608', 116.38910000000001, datetime.timedelta(seconds=6983, microseconds=346000)),
 ('si2471', 115.1609, datetime.timedelta(seconds=6909, microseconds=654000)),
 ('nk3214', 90.9545, datetime.timedelta(seconds=5457, microseconds=270000)),
 ('fm2859', 47.8448, datetime.timedelta(seconds=2870, microseconds=688000)),
 ('mh4605', 45.82959999999999, datetime.timedelta(seconds=2749, microseconds=776000)),
 ('cl4537', 31.2095, datetime.timedelta(seconds=1872, microseconds=570000)),
 ('ss7544', 1.0477, datetime.timedelta(seconds=62, microseconds=862000)),
 ('dff9', 0.3378, datetime.timedelta(seconds=20, microseconds=268000))]

### Sales and Orders Analysis Breakdown

| <img src="classic_models.jpg" width=700px> |
| :---: |
| __Classic Model Schema__ |

#### How bad are the shipping delays?

In [25]:
%%sql
use classicmodels;

with one as (
    select
        orderNumber,
        shippedDate,
        orderDate,
        datediff(shippedDate, orderDate) as shipping_days,
        (select customerName from customers where
                                                customers.customerNumber=orders.customerNumber) as customerName
        from orders
        where shippedDate is not null
)
select
    *
from
    one
order by shipping_days desc;

 * mysql+pymysql://root:***@localhost
0 rows affected.
312 rows affected.

[(10165, datetime.date(2003, 12, 26), datetime.date(2003, 10, 22), 65, 'Dragon Souveniers, Ltd.'),
 (10210, datetime.date(2004, 1, 20), datetime.date(2004, 1, 12), 8, 'Osaka Souveniers Co.'),
 (10258, datetime.date(2004, 6, 23), datetime.date(2004, 6, 15), 8, 'Tokyo Collectables, Ltd'),
 (10240, datetime.date(2004, 4, 20), datetime.date(2004, 4, 13), 7, 'Osaka Souveniers Co.'),
 (10339, datetime.date(2004, 11, 30), datetime.date(2004, 11, 23), 7, 'Tokyo Collectables, Ltd'),
 (10121, datetime.date(2003, 5, 13), datetime.date(2003, 5, 7), 6, 'Reims Collectables'),
 (10133, datetime.date(2003, 7, 3), datetime.date(2003, 6, 27), 6, 'Euro+ Shopping Channel'),
 (10138, datetime.date(2003, 7, 13), datetime.date(2003, 7, 7), 6, "Kelly's Gift Shop"),
 (10140, datetime.date(2003, 7, 30), datetime.date(2003, 7, 24), 6, 'Technics Stores Inc.'),
 (10145, datetime.date(2003, 8, 31), datetime.date(2003, 8, 25), 6, 'Toys4GrownUps.com'),
 (10152, datetime.date(2003, 10, 1), datetime.date(2003, 9, 25), 6, 'Australian Gift Network, Co'),
 (10154, datetime.date(2003, 10, 8), datetime.date(2003, 10, 2), 6, 'Boards & Toys Co.'),
 (10159, datetime.date(2003, 10, 16), datetime.date(2003, 10, 10), 6, 'Corporate Gift Ideas Co.'),
 (10160, datetime.date(2003, 10, 17), datetime.date(2003, 10, 11), 6, "Men 'R' US Retailers, Ltd."),
 (10166, datetime.date(2003, 10, 27), datetime.date(2003, 10, 21), 6, 'FunGiftIdeas.com'),
 (10172, datetime.date(2003, 11, 11), datetime.date(2003, 11, 5), 6, 'Gift Depot Inc.'),
 (10176, datetime.date(2003, 11, 12), datetime.date(2003, 11, 6), 6, "L'ordine Souveniers"),
 (10182, datetime.date(2003, 11, 18), datetime.date(2003, 11, 12), 6, 'Mini Gifts Distributors Ltd.'),
 (10184, datetime.date(2003, 11, 20), datetime.date(2003, 11, 14), 6, 'Iberia Gift Imports, Corp.'),
 (10185, datetime.date(2003, 11, 20), datetime.date(2003, 11, 14), 6, 'Mini Creations Ltd.'),
 (10188, datetime.date(2003, 11, 24), datetime.date(2003, 11, 18), 6, 'Herkku Gifts'),
 (10189, datetime.date(2003, 11, 24), datetime.date(2003, 11, 18), 6, 'Toys4GrownUps.com'),
 (10193, datetime.date(2003, 11, 27), datetime.date(2003, 11, 21), 6, 'Australian Collectables, Ltd'),
 (10198, datetime.date(2003, 12, 3), datetime.date(2003, 11, 27), 6, 'Cruz & Sons Co.'),
 (10227, datetime.date(2004, 3, 8), datetime.date(2004, 3, 2), 6, 'Saveley & Henriot, Co.'),
 (10231, datetime.date(2004, 3, 25), datetime.date(2004, 3, 19), 6, 'CAF Imports'),
 (10241, datetime.date(2004, 4, 19), datetime.date(2004, 4, 13), 6, 'Mini Caravy'),
 (10251, datetime.date(2004, 5, 24), datetime.date(2004, 5, 18), 6, 'Tekni Collectables Inc.'),
 (10275, datetime.date(2004, 7, 29), datetime.date(2004, 7, 23), 6, 'La Rochelle Gifts'),
 (10276, datetime.date(2004, 8, 8), datetime.date(2004, 8, 2), 6, 'Online Mini Collectables'),
 (10279, datetime.date(2004, 8, 15), datetime.date(2004, 8, 9), 6, 'Euro+ Shopping Channel'),
 (10290, datetime.date(2004, 9, 13), datetime.date(2004, 9, 7), 6, 'Auto-Moto Classics Inc.'),
 (10291, datetime.date(2004, 9, 14), datetime.date(2004, 9, 8), 6, 'Scandinavian Gift Ideas'),
 (10304, datetime.date(2004, 10, 17), datetime.date(2004, 10, 11), 6, 'Auto Associés & Cie.'),
 (10307, datetime.date(2004, 10, 20), datetime.date(2004, 10, 14), 6, 'Classic Gift Ideas, Inc'),
 (10316, datetime.date(2004, 11, 7), datetime.date(2004, 11, 1), 6, 'giftsbymail.co.uk'),
 (10317, datetime.date(2004, 11, 8), datetime.date(2004, 11, 2), 6, 'Technics Stores Inc.'),
 (10322, datetime.date(2004, 11, 10), datetime.date(2004, 11, 4), 6, 'Online Diecast Creations Co.'),
 (10328, datetime.date(2004, 11, 18), datetime.date(2004, 11, 12), 6, 'Rovelli Gifts'),
 (10331, datetime.date(2004, 11, 23), datetime.date(2004, 11, 17), 6, 'Motor Mint Distributors Inc.'),
 (10352, datetime.date(2004, 12, 9), datetime.date(2004, 12, 3), 6, 'Auto-Moto Classics Inc.'),
 (10355, datetime.date(2004, 12, 13), datetime.date(2004, 12, 7), 6, 'Euro+ Shopping Channel'),
 (10358, datetime.date(2004, 12, 16), datetime.date(2004, 12, 10), 6, 'Euro+ Shopping Channel'),
 (10373, datetime.date(2005, 2, 6), datetime.date(2005, 1, 31), 6, 'Oulu Toy Supplies, Inc.'),
 (10388, datetime.date(2005, 3, 9), datetime.date(2005, 3, 3), 6, 'FunGiftIdeas.com'),
 (10391, datetime.date(2005, 3, 15), datetime.date(2005, 3, 9), 6, "Anna's Decorations, Ltd"),
 (10395, datetime.date(2005, 3, 23), datetime.date(2005, 3, 17), 6, 'Lyon Souveniers'),
 (10405, datetime.date(2005, 4, 20), datetime.date(2005, 4, 14), 6, 'Mini Caravy'),
 (10406, datetime.date(2005, 4, 21), datetime.date(2005, 4, 15), 6, 'Danish Wholesale Imports'),
 (10417, datetime.date(2005, 5, 19), datetime.date(2005, 5, 13), 6, 'Euro+ Shopping Channel'),
 (10108, datetime.date(2003, 3, 8), datetime.date(2003, 3, 3), 5, 'Cruz & Sons Co.'),
 (10111, datetime.date(2003, 3, 30), datetime.date(2003, 3, 25), 5, 'Mini Wheels Co.'),
 (10112, datetime.date(2003, 3, 29), datetime.date(2003, 3, 24), 5, 'Volvo Model Replicas, Co'),
 (10118, datetime.date(2003, 4, 26), datetime.date(2003, 4, 21), 5, 'Enaco Distributors'),
 (10122, datetime.date(2003, 5, 13), datetime.date(2003, 5, 8), 5, 'Marseille Mini Autos'),
 (10126, datetime.date(2003, 6, 2), datetime.date(2003, 5, 28), 5, 'Corrida Auto Replicas, Ltd'),
 (10128, datetime.date(2003, 6, 11), datetime.date(2003, 6, 6), 5, 'Euro+ Shopping Channel'),
 (10130, datetime.date(2003, 6, 21), datetime.date(2003, 6, 16), 5, 'Auto-Moto Classics Inc.'),
 (10131, datetime.date(2003, 6, 21), datetime.date(2003, 6, 16), 5, 'Gift Ideas Corp.'),
 (10139, datetime.date(2003, 7, 21), datetime.date(2003, 7, 16), 5, 'Souveniers And Things Co.'),
 (10142, datetime.date(2003, 8, 13), datetime.date(2003, 8, 8), 5, 'Mini Gifts Distributors Ltd.'),
 (10149, datetime.date(2003, 9, 17), datetime.date(2003, 9, 12), 5, 'Signal Collectibles Ltd.'),
 (10153, datetime.date(2003, 10, 3), datetime.date(2003, 9, 28), 5, 'Euro+ Shopping Channel'),
 (10157, datetime.date(2003, 10, 14), datetime.date(2003, 10, 9), 5, 'Frau da Collezione'),
 (10158, datetime.date(2003, 10, 15), datetime.date(2003, 10, 10), 5, 'Baane Mini Imports'),
 (10169, datetime.date(2003, 11, 9), datetime.date(2003, 11, 4), 5, "Anna's Decorations, Ltd"),
 (10177, datetime.date(2003, 11, 12), datetime.date(2003, 11, 7), 5, 'CAF Imports'),
 (10192, datetime.date(2003, 11, 25), datetime.date(2003, 11, 20), 5, 'Online Diecast Creations Co.'),
 (10196, datetime.date(2003, 12, 1), datetime.date(2003, 11, 26), 5, 'Super Scale Inc.'),
 (10197, datetime.date(2003, 12, 1), datetime.date(2003, 11, 26), 5, 'Enaco Distributors'),
 (10199, datetime.date(2003, 12, 6), datetime.date(2003, 12, 1), 5, 'West Coast Collectables Co.'),
 (10200, datetime.date(2003, 12, 6), datetime.date(2003, 12, 1), 5, 'King Kong Collectables, Co.'),
 (10203, datetime.date(2003, 12, 7), datetime.date(2003, 12, 2), 5, 'Euro+ Shopping Channel'),
 (10213, datetime.date(2004, 1, 27), datetime.date(2004, 1, 22), 5, 'Double Decker Gift Stores, Ltd'),
 (10224, datetime.date(2004, 2, 26), datetime.date(2004, 2, 21), 5, 'Daedalus Designs Imports'),
 (10226, datetime.date(2004, 3, 2), datetime.date(2004, 2, 26), 5, 'Collectable Mini Designs Co.'),
 (10230, datetime.date(2004, 3, 20), datetime.date(2004, 3, 15), 5, 'Blauer See Auto, Co.'),
 (10232, datetime.date(2004, 3, 25), datetime.date(2004, 3, 20), 5, 'giftsbymail.co.uk'),
 (10236, datetime.date(2004, 4, 8), datetime.date(2004, 4, 3), 5, 'Motor Mint Distributors Inc.'),
 (10237, datetime.date(2004, 4, 10), datetime.date(2004, 4, 5), 5, 'Vitachrome Inc.'),
 (10239, datetime.date(2004, 4, 17), datetime.date(2004, 4, 12), 5, 'Oulu Toy Supplies, Inc.'),
 (10242, datetime.date(2004, 4, 25), datetime.date(2004, 4, 20), 5, 'Microscale Inc.'),
 (10244, datetime.date(2004, 5, 4), datetime.date(2004, 4, 29), 5, 'Euro+ Shopping Channel'),
 (10245, datetime.date(2004, 5, 9), datetime.date(2004, 5, 4), 5, 'Super Scale Inc.'),
 (10255, datetime.date(2004, 6, 9), datetime.date(2004, 6, 4), 5, 'Mini Caravy'),
 (10261, datetime.date(2004, 6, 22), datetime.date(2004, 6, 17), 5, 'Québec Home Shopping Network'),
 (10265, datetime.date(2004, 7, 7), datetime.date(2004, 7, 2), 5, 'Australian Collectables, Ltd'),
 (10270, datetime.date(2004, 7, 24), datetime.date(2004, 7, 19), 5, 'Souveniers And Things Co.'),
 (10284, datetime.date(2004, 8, 26), datetime.date(2004, 8, 21), 5, 'Norway Gifts By Mail, Co.'),
 (10293, datetime.date(2004, 9, 14), datetime.date(2004, 9, 9), 5, 'Amica Models & Co.'),
 (10297, datetime.date(2004, 9, 21), datetime.date(2004, 9, 16), 5, 'Clover Collections, Co.'),
 (10300, datetime.date(2003, 10, 9), datetime.date(2003, 10, 4), 5, 'Blauer See Auto, Co.'),
 (10308, datetime.date(2004, 10, 20), datetime.date(2004, 10, 15), 5, 'Mini Classics'),
 (10318, datetime.date(2004, 11, 7), datetime.date(2004, 11, 2), 5, 'Diecast Classics Inc.'),
 (10330, datetime.date(2004, 11, 21), datetime.date(2004, 11, 16), 5, 'Cruz & Sons Co.'),
 (10337, datetime.date(2004, 11, 26), datetime.date(2004, 11, 21), 5, 'Classic Legends Inc.'),
 (10338, datetime.date(2004, 11, 27), datetime.date(2004, 11, 22), 5, 'Royale Belge'),
 (10341, datetime.date(2004, 11, 29), datetime.date(2004, 11, 24), 5, 'Salzburg Collectables'),
 (10342, datetime.date(2004, 11, 29), datetime.date(2004, 11, 24), 5, 'Australian Collectors, Co.'),
 (10362, datetime.date(2005, 1, 10), datetime.date(2005, 1, 5), 5, 'Technics Stores Inc.'),
 (10368, datetime.date(2005, 1, 24), datetime.date(2005, 1, 19), 5, 'Mini Gifts Distributors Ltd.'),
 (10370, datetime.date(2005, 1, 25), datetime.date(2005, 1, 20), 5, "Anna's Decorations, Ltd"),
 (10376, datetime.date(2005, 2, 13), datetime.date(2005, 2, 8), 5, 'Boards & Toys Co.'),
 (10386, datetime.date(2005, 3, 6), datetime.date(2005, 3, 1), 5, 'Euro+ Shopping Channel'),
 (10389, datetime.date(2005, 3, 8), datetime.date(2005, 3, 3), 5, 'Scandinavian Gift Ideas'),
 (10396, datetime.date(2005, 3, 28), datetime.date(2005, 3, 23), 5, 'Mini Gifts Distributors Ltd.'),
 (10402, datetime.date(2005, 4, 12), datetime.date(2005, 4, 7), 5, 'Auto Canal+ Petit'),
 (10408, datetime.date(2005, 4, 27), datetime.date(2005, 4, 22), 5, 'Tokyo Collectables, Ltd'),
 (10411, datetime.date(2005, 5, 6), datetime.date(2005, 5, 1), 5, 'Québec Home Shopping Network'),
 (10100, datetime.date(2003, 1, 10), datetime.date(2003, 1, 6), 4, 'Online Diecast Creations Co.'),
 (10102, datetime.date(2003, 1, 14), datetime.date(2003, 1, 10), 4, 'Vitachrome Inc.'),
 (10103, datetime.date(2003, 2, 2), datetime.date(2003, 1, 29), 4, 'Baane Mini Imports'),
 (10106, datetime.date(2003, 2, 21), datetime.date(2003, 2, 17), 4, 'Rovelli Gifts'),
 (10119, datetime.date(2003, 5, 2), datetime.date(2003, 4, 28), 4, 'Salzburg Collectables'),
 (10124, datetime.date(2003, 5, 25), datetime.date(2003, 5, 21), 4, 'Signal Gift Stores'),
 (10134, datetime.date(2003, 7, 5), datetime.date(2003, 7, 1), 4, 'Lyon Souveniers'),
 (10137, datetime.date(2003, 7, 14), datetime.date(2003, 7, 10), 4, 'Reims Collectables'),
 (10147, datetime.date(2003, 9, 9), datetime.date(2003, 9, 5), 4, 'Collectables For Less Inc.'),
 (10148, datetime.date(2003, 9, 15), datetime.date(2003, 9, 11), 4, "Anna's Decorations, Ltd"),
 (10163, datetime.date(2003, 10, 24), datetime.date(2003, 10, 20), 4, 'Classic Legends Inc.'),
 (10168, datetime.date(2003, 11, 1), datetime.date(2003, 10, 28), 4, 'Technics Stores Inc.'),
 (10173, datetime.date(2003, 11, 9), datetime.date(2003, 11, 5), 4, 'Rovelli Gifts'),
 (10174, datetime.date(2003, 11, 10), datetime.date(2003, 11, 6), 4, 'Australian Gift Network, Co'),
 (10186, datetime.date(2003, 11, 18), datetime.date(2003, 11, 14), 4, 'Double Decker Gift Stores, Ltd'),
 (10191, datetime.date(2003, 11, 24), datetime.date(2003, 11, 20), 4, 'Toms Spezialitäten, Ltd'),
 (10202, datetime.date(2003, 12, 6), datetime.date(2003, 12, 2), 4, 'GiftsForHim.com'),
 (10205, datetime.date(2003, 12, 7), datetime.date(2003, 12, 3), 4, 'Euro+ Shopping Channel'),
 (10220, datetime.date(2004, 2, 16), datetime.date(2004, 2, 12), 4, 'Clover Collections, Co.'),
 (10223, datetime.date(2004, 2, 24), datetime.date(2004, 2, 20), 4, 'Australian Collectors, Co.'),
 (10233, datetime.date(2004, 4, 2), datetime.date(2004, 3, 29), 4, 'Tekni Collectables Inc.'),
 (10235, datetime.date(2004, 4, 6), datetime.date(2004, 4, 2), 4, 'Royal Canadian Collectables, Ltd.'),
 (10250, datetime.date(2004, 5, 15), datetime.date(2004, 5, 11), 4, 'The Sharp Gifts Warehouse'),
 (10263, datetime.date(2004, 7, 2), datetime.date(2004, 6, 28), 4, 'Gift Depot Inc.'),
 (10266, datetime.date(2004, 7, 10), datetime.date(2004, 7, 6), 4, "L'ordine Souveniers"),
 (10281, datetime.date(2004, 8, 23), datetime.date(2004, 8, 19), 4, 'Diecast Classics Inc.'),
 (10285, datetime.date(2004, 8, 31), datetime.date(2004, 8, 27), 4, "Marta's Replicas Co."),
 (10286, datetime.date(2004, 9, 1), datetime.date(2004, 8, 28), 4, "La Corne D'abondance, Co."),
 (10288, datetime.date(2004, 9, 5), datetime.date(2004, 9, 1), 4, 'Handji Gifts& Co'),
 (10294, datetime.date(2004, 9, 14), datetime.date(2004, 9, 10), 4, 'Online Mini Collectables'),
 (10295, datetime.date(2004, 9, 14), datetime.date(2004, 9, 10), 4, 'Gifts4AllAges.com'),
 (10298, datetime.date(2004, 10, 1), datetime.date(2004, 9, 27), 4, 'Atelier graphique'),
 (10311, datetime.date(2004, 10, 20), datetime.date(2004, 10, 16), 4, 'Euro+ Shopping Channel'),
 (10320, datetime.date(2004, 11, 7), datetime.date(2004, 11, 3), 4, 'Volvo Model Replicas, Co'),
 (10323, datetime.date(2004, 11, 9), datetime.date(2004, 11, 5), 4, 'Blauer See Auto, Co.'),
 (10335, datetime.date(2004, 11, 23), datetime.date(2004, 11, 19), 4, 'Mini Gifts Distributors Ltd.'),
 (10336, datetime.date(2004, 11, 24), datetime.date(2004, 11, 20), 4, "La Corne D'abondance, Co."),
 (10344, datetime.date(2004, 11, 29), datetime.date(2004, 11, 25), 4, 'Marseille Mini Autos'),
 (10348, datetime.date(2004, 11, 5), datetime.date(2004, 11, 1), 4, 'Corrida Auto Replicas, Ltd'),
 (10351, datetime.date(2004, 12, 7), datetime.date(2004, 12, 3), 4, 'Stylish Desk Decors, Co.'),
 (10357, datetime.date(2004, 12, 14), datetime.date(2004, 12, 10), 4, 'Mini Gifts Distributors Ltd.'),
 (10363, datetime.date(2005, 1, 10), datetime.date(2005, 1, 6), 4, 'Suominen Souveniers'),
 (10365, datetime.date(2005, 1, 11), datetime.date(2005, 1, 7), 4, 'Mini Creations Ltd.'),
 (10367, datetime.date(2005, 1, 16), datetime.date(2005, 1, 12), 4, 'Toys4GrownUps.com'),
 (10369, datetime.date(2005, 1, 24), datetime.date(2005, 1, 20), 4, 'Collectables For Less Inc.'),
 (10384, datetime.date(2005, 2, 27), datetime.date(2005, 2, 23), 4, 'Corporate Gift Ideas Co.'),
 (10387, datetime.date(2005, 3, 6), datetime.date(2005, 3, 2), 4, 'Dragon Souveniers, Ltd.'),
 (10394, datetime.date(2005, 3, 19), datetime.date(2005, 3, 15), 4, 'Euro+ Shopping Channel'),
 (10397, datetime.date(2005, 4, 1), datetime.date(2005, 3, 28), 4, 'Alpha Cognac'),
 (10413, datetime.date(2005, 5, 9), datetime.date(2005, 5, 5), 4, 'Gift Depot Inc.'),
 (10416, datetime.date(2005, 5, 14), datetime.date(2005, 5, 10), 4, "L'ordine Souveniers"),
 (10418, datetime.date(2005, 5, 20), datetime.date(2005, 5, 16), 4, 'Extreme Desk Decorations, Ltd'),
 (10115, datetime.date(2003, 4, 7), datetime.date(2003, 4, 4), 3, 'Classic Legends Inc.'),
 (10125, datetime.date(2003, 5, 24), datetime.date(2003, 5, 21), 3, 'Australian Collectors, Co.'),
 (10127, datetime.date(2003, 6, 6), datetime.date(2003, 6, 3), 3, 'Muscle Machine Inc'),
 (10132, datetime.date(2003, 6, 28), datetime.date(2003, 6, 25), 3, 'Down Under Souveniers, Inc'),
 (10141, datetime.date(2003, 8, 4), datetime.date(2003, 8, 1), 3, 'Suominen Souveniers'),
 (10146, datetime.date(2003, 9, 6), datetime.date(2003, 9, 3), 3, 'Gift Ideas Corp.'),
 (10151, datetime.date(2003, 9, 24), datetime.date(2003, 9, 21), 3, 'Oulu Toy Supplies, Inc.'),
 (10156, datetime.date(2003, 10, 11), datetime.date(2003, 10, 8), 3, 'Euro+ Shopping Channel'),
 (10161, datetime.date(2003, 10, 20), datetime.date(2003, 10, 17), 3, 'Heintze Collectables'),
 (10170, datetime.date(2003, 11, 7), datetime.date(2003, 11, 4), 3, 'Mini Auto Werke'),
 (10175, datetime.date(2003, 11, 9), datetime.date(2003, 11, 6), 3, 'Stylish Desk Decors, Co.'),
 (10180, datetime.date(2003, 11, 14), datetime.date(2003, 11, 11), 3, 'Daedalus Designs Imports'),
 (10181, datetime.date(2003, 11, 15), datetime.date(2003, 11, 12), 3, 'Herkku Gifts'),
 (10195, datetime.date(2003, 11, 28), datetime.date(2003, 11, 25), 3, 'Mini Classics'),
 (10206, datetime.date(2003, 12, 8), datetime.date(2003, 12, 5), 3, 'Canadian Gift Exchange Network'),
 (10209, datetime.date(2004, 1, 12), datetime.date(2004, 1, 9), 3, "Men 'R' US Retailers, Ltd."),
 (10211, datetime.date(2004, 1, 18), datetime.date(2004, 1, 15), 3, 'Auto Canal+ Petit'),
 (10214, datetime.date(2004, 1, 29), datetime.date(2004, 1, 26), 3, 'Corrida Auto Replicas, Ltd'),
 (10215, datetime.date(2004, 2, 1), datetime.date(2004, 1, 29), 3, 'West Coast Collectables Co.'),
 (10228, datetime.date(2004, 3, 13), datetime.date(2004, 3, 10), 3, 'Cambridge Collectables Co.'),
 (10234, datetime.date(2004, 4, 2), datetime.date(2004, 3, 30), 3, 'Extreme Desk Decorations, Ltd'),
 (10247, datetime.date(2004, 5, 8), datetime.date(2004, 5, 5), 3, 'Suominen Souveniers'),
 (10249, datetime.date(2004, 5, 11), datetime.date(2004, 5, 8), 3, 'Cambridge Collectables Co.'),
 (10252, datetime.date(2004, 5, 29), datetime.date(2004, 5, 26), 3, 'Auto Canal+ Petit'),
 (10271, datetime.date(2004, 7, 23), datetime.date(2004, 7, 20), 3, 'Mini Gifts Distributors Ltd.'),
 (10278, datetime.date(2004, 8, 9), datetime.date(2004, 8, 6), 3, 'Signal Gift Stores'),
 (10283, datetime.date(2004, 8, 23), datetime.date(2004, 8, 20), 3, 'Royal Canadian Collectables, Ltd.'),
 (10292, datetime.date(2004, 9, 11), datetime.date(2004, 9, 8), 3, 'Land of Toys Inc.'),
 (10301, datetime.date(2003, 10, 8), datetime.date(2003, 10, 5), 3, 'Norway Gifts By Mail, Co.'),
 (10303, datetime.date(2004, 10, 9), datetime.date(2004, 10, 6), 3, 'Iberia Gift Imports, Corp.'),
 (10306, datetime.date(2004, 10, 17), datetime.date(2004, 10, 14), 3, 'AV Stores, Co.'),
 (10309, datetime.date(2004, 10, 18), datetime.date(2004, 10, 15), 3, 'Baane Mini Imports'),
 (10313, datetime.date(2004, 10, 25), datetime.date(2004, 10, 22), 3, 'Canadian Gift Exchange Network'),
 (10319, datetime.date(2004, 11, 6), datetime.date(2004, 11, 3), 3, 'Microscale Inc.'),
 (10321, datetime.date(2004, 11, 7), datetime.date(2004, 11, 4), 3, 'FunGiftIdeas.com'),
 (10324, datetime.date(2004, 11, 8), datetime.date(2004, 11, 5), 3, 'Vitachrome Inc.'),
 (10325, datetime.date(2004, 11, 8), datetime.date(2004, 11, 5), 3, 'Baane Mini Imports'),
 (10327, datetime.date(2004, 11, 13), datetime.date(2004, 11, 10), 3, 'Danish Wholesale Imports'),
 (10350, datetime.date(2004, 12, 5), datetime.date(2004, 12, 2), 3, 'Euro+ Shopping Channel'),
 (10356, datetime.date(2004, 12, 12), datetime.date(2004, 12, 9), 3, 'Lyon Souveniers'),
 (10359, datetime.date(2004, 12, 18), datetime.date(2004, 12, 15), 3, 'Reims Collectables'),
 (10361, datetime.date(2004, 12, 20), datetime.date(2004, 12, 17), 3, 'Souveniers And Things Co.'),
 (10364, datetime.date(2005, 1, 9), datetime.date(2005, 1, 6), 3, 'Marseille Mini Autos'),
 (10375, datetime.date(2005, 2, 6), datetime.date(2005, 2, 3), 3, 'La Rochelle Gifts'),
 (10377, datetime.date(2005, 2, 12), datetime.date(2005, 2, 9), 3, 'Toys of Finland, Co.'),
 (10383, datetime.date(2005, 2, 25), datetime.date(2005, 2, 22), 3, 'Euro+ Shopping Channel'),
 (10390, datetime.date(2005, 3, 7), datetime.date(2005, 3, 4), 3, 'Mini Gifts Distributors Ltd.'),
 (10393, datetime.date(2005, 3, 14), datetime.date(2005, 3, 11), 3, 'Down Under Souveniers, Inc'),
 (10400, datetime.date(2005, 4, 4), datetime.date(2005, 4, 1), 3, 'The Sharp Gifts Warehouse'),
 (10403, datetime.date(2005, 4, 11), datetime.date(2005, 4, 8), 3, 'UK Collectables, Ltd.'),
 (10404, datetime.date(2005, 4, 11), datetime.date(2005, 4, 8), 3, 'Down Under Souveniers, Inc'),

Lets look at summaries for customers.

In [26]:
%%sql

with one as (
    select
        orderNumber,
        shippedDate,
        orderDate,
        datediff(shippedDate, orderDate) as shipping_days,
        (select customerName from customers where
                                                customers.customerNumber=orders.customerNumber) as customerName
        from orders
        where shippedDate is not null
)
select
    customerName,
    count(*) as total_orders,
    min(shipping_days) as min_shipping_days,
    max(shipping_days) as max_shipping_days,
    avg(shipping_days) as avg_shipping_days
from
    one
group by customerName
order by avg_shipping_days desc;

 * mysql+pymysql://root:***@localhost
98 rows affected.

[('Dragon Souveniers, Ltd.', 5, 1, 65, Decimal('14.6000')),
 ('Osaka Souveniers Co.', 2, 7, 8, Decimal('7.5000')),
 ('Mini Caravy', 3, 5, 6, Decimal('5.6667')),
 ('Auto-Moto Classics Inc.', 3, 5, 6, Decimal('5.6667')),
 ('Tokyo Collectables, Ltd', 4, 2, 8, Decimal('5.5000')),
 ('Scandinavian Gift Ideas', 2, 5, 6, Decimal('5.5000')),
 ('CAF Imports', 2, 5, 6, Decimal('5.5000')),
 ('Boards & Toys Co.', 2, 5, 6, Decimal('5.5000')),
 ('giftsbymail.co.uk', 2, 5, 6, Decimal('5.5000')),
 ('Cruz & Sons Co.', 3, 5, 6, Decimal('5.3333')),
 ('Toys4GrownUps.com', 3, 4, 6, Decimal('5.3333')),
 ('Technics Stores Inc.', 4, 4, 6, Decimal('5.2500')),
 ('Online Diecast Creations Co.', 3, 4, 6, Decimal('5.0000')),
 ('FunGiftIdeas.com', 3, 3, 6, Decimal('5.0000')),
 ('Tekni Collectables Inc.', 2, 4, 6, Decimal('5.0000')),
 ("Anna's Decorations, Ltd", 4, 4, 6, Decimal('5.0000')),
 ('Super Scale Inc.', 2, 5, 5, Decimal('5.0000')),
 ('Online Mini Collectables', 2, 4, 6, Decimal('5.0000')),
 ('Rovelli Gifts', 3, 4, 6, Decimal('4.6667')),
 ("L'ordine Souveniers", 3, 4, 6, Decimal('4.6667')),
 ('Gift Depot Inc.', 3, 4, 6, Decimal('4.6667')),
 ('Australian Collectables, Ltd', 3, 3, 6, Decimal('4.6667')),
 ('Oulu Toy Supplies, Inc.', 3, 3, 6, Decimal('4.6667')),
 ('Iberia Gift Imports, Corp.', 2, 3, 6, Decimal('4.5000')),
 ('Clover Collections, Co.', 2, 4, 5, Decimal('4.5000')),
 ('Double Decker Gift Stores, Ltd', 2, 4, 5, Decimal('4.5000')),
 ("Men 'R' US Retailers, Ltd.", 2, 3, 6, Decimal('4.5000')),
 ('Souveniers And Things Co.', 3, 3, 5, Decimal('4.3333')),
 ('Lyon Souveniers', 3, 3, 6, Decimal('4.3333')),
 ('Blauer See Auto, Co.', 4, 2, 5, Decimal('4.0000')),
 ('Marseille Mini Autos', 3, 3, 5, Decimal('4.0000')),
 ('Vitachrome Inc.', 3, 3, 5, Decimal('4.0000')),
 ('Mini Creations Ltd.', 3, 2, 6, Decimal('4.0000')),
 ('Mini Classics', 2, 3, 5, Decimal('4.0000')),
 ('West Coast Collectables Co.', 2, 3, 5, Decimal('4.0000')),
 ('Norway Gifts By Mail, Co.', 2, 3, 5, Decimal('4.0000')),
 ('Classic Legends Inc.', 3, 3, 5, Decimal('4.0000')),
 ('Auto Associés & Cie.', 2, 2, 6, Decimal('4.0000')),
 ('Corrida Auto Replicas, Ltd', 3, 3, 5, Decimal('4.0000')),
 ('Québec Home Shopping Network', 3, 2, 5, Decimal('4.0000')),
 ('Microscale Inc.', 2, 3, 5, Decimal('4.0000')),
 ('Motor Mint Distributors Inc.', 3, 1, 6, Decimal('4.0000')),
 ('Daedalus Designs Imports', 2, 3, 5, Decimal('4.0000')),
 ('Classic Gift Ideas, Inc', 2, 2, 6, Decimal('4.0000')),
 ('Baane Mini Imports', 4, 3, 5, Decimal('3.7500')),
 ('Auto Canal+ Petit', 3, 3, 5, Decimal('3.6667')),
 ('Diecast Classics Inc.', 3, 2, 5, Decimal('3.6667')),
 ('Enaco Distributors', 3, 1, 5, Decimal('3.6667')),
 ('Australian Gift Network, Co', 3, 1, 6, Decimal('3.6667')),
 ('Euro+ Shopping Channel', 24, 1, 6, Decimal('3.6250')),
 ('Signal Collectibles Ltd.', 2, 2, 5, Decimal('3.5000')),
 ('Frau da Collezione', 2, 2, 5, Decimal('3.5000')),
 ('Amica Models & Co.', 2, 2, 5, Decimal('3.5000')),
 ('Royal Canadian Collectables, Ltd.', 2, 3, 4, Decimal('3.5000')),
 ('La Rochelle Gifts', 3, 1, 6, Decimal('3.3333')),
 ('Suominen Souveniers', 3, 3, 4, Decimal('3.3333')),
 ('Volvo Model Replicas, Co', 3, 1, 5, Decimal('3.3333')),
 ('Herkku Gifts', 3, 1, 6, Decimal('3.3333')),
 ('Salzburg Collectables', 4, 2, 5, Decimal('3.2500')),
 ('Reims Collectables', 5, 1, 6, Decimal('3.2000')),
 ('Corporate Gift Ideas Co.', 4, 1, 6, Decimal('3.0000')),
 ('King Kong Collectables, Co.', 2, 1, 5, Decimal('3.0000')),
 ('Toms Spezialitäten, Ltd', 2, 2, 4, Decimal('3.0000')),
 ('Saveley & Henriot, Co.', 3, 1, 6, Decimal('3.0000')),
 ('Collectables For Less Inc.', 3, 1, 4, Decimal('3.0000')),
 ("Kelly's Gift Shop", 4, 2, 6, Decimal('3.0000')),
 ('Canadian Gift Exchange Network', 2, 3, 3, Decimal('3.0000')),
 ('Gift Ideas Corp.', 3, 1, 5, Decimal('3.0000')),
 ('Stylish Desk Decors, Co.', 3, 2, 4, Decimal('3.0000')),
 ('Collectable Mini Designs Co.', 2, 1, 5, Decimal('3.0000')),
 ('Australian Collectors, Co.', 5, 1, 5, Decimal('3.0000')),
 ('Cambridge Collectables Co.', 2, 3, 3, Decimal('3.0000')),
 ("La Corne D'abondance, Co.", 3, 1, 4, Decimal('3.0000')),
 ('Extreme Desk Decorations, Ltd', 3, 2, 4, Decimal('3.0000')),
 ("Marta's Replicas Co.", 2, 2, 4, Decimal('3.0000')),
 ('Mini Gifts Distributors Ltd.', 16, 1, 6, Decimal('2.8750')),
 ('Alpha Cognac', 3, 2, 4, Decimal('2.6667')),
 ('Signal Gift Stores', 3, 1, 4, Decimal('2.6667')),
 ('Mini Wheels Co.', 3, 1, 5, Decimal('2.6667')),
 ('The Sharp Gifts Warehouse', 3, 1, 4, Decimal('2.6667')),
 ('Danish Wholesale Imports', 5, 1, 6, Decimal('2.6000')),
 ('GiftsForHim.com', 2, 1, 4, Decimal('2.5000')),
 ('Royale Belge', 4, 1, 5, Decimal('2.5000')),
 ('Gifts4AllAges.com', 2, 1, 4, Decimal('2.5000')),
 ('Mini Auto Werke', 3, 2, 3, Decimal('2.3333')),
 ('Atelier graphique', 3, 1, 4, Decimal('2.3333')),
 ('Muscle Machine Inc', 4, 2, 3, Decimal('2.2500')),
 ('Handji Gifts& Co', 4, 1, 4, Decimal('2.2500')),
 ('Down Under Souveniers, Inc', 5, 1, 3, Decimal('2.2000')),
 ('Heintze Collectables', 2, 1, 3, Decimal('2.0000')),
 ('Vida Sport, Ltd', 2, 2, 2, Decimal('2.0000')),
 ('Diecast Collectables', 2, 2, 2, Decimal('2.0000')),
 ('AV Stores, Co.', 3, 1, 3, Decimal('2.0000')),
 ('Land of Toys Inc.', 3, 1, 3, Decimal('2.0000')),
 ('UK Collectables, Ltd.', 3, 1, 3, Decimal('1.6667')),
 ('Toys of Finland, Co.', 3, 1, 3, Decimal('1.6667')),
 ('Petit Auto', 2, 1, 1, Decimal('1.0000')),
 ('Bavarian Collectables Imports, Co.', 1, 1, 1, Decimal('1.0000'))]

#### Sales by Year, Quarter, Month

In [27]:
%%sql

with one as (
    select
        orderNumber, quantityOrdered, priceEach, quantityOrdered*priceEach as revenue,
        shippedDate,
        year(shippedDate) as shipYear,
        quarter(shippedDate) as shipQuarter,
        month(shippedDate) as shipMonth
    from orders join orderdetails using(orderNumber)
    where shippedDate is not null
)
select
    shipYear, shipQuarter, shipMonth,
    concat("$", format(sum(revenue), 2)) as total_revenue
from
    one
group by shipYear, shipQuarter, shipMonth
order by shipYear, shipQuarter, shipMonth;

 * mysql+pymysql://root:***@localhost
29 rows affected.

[(2003, 1, 1, '$26,267.62'),
 (2003, 1, 2, '$218,828.79'),
 (2003, 1, 3, '$160,517.14'),
 (2003, 2, 4, '$104,158.23'),
 (2003, 2, 5, '$203,993.99'),
 (2003, 2, 6, '$185,236.65'),
 (2003, 3, 7, '$224,306.40'),
 (2003, 3, 8, '$178,257.11'),
 (2003, 3, 9, '$181,936.68'),
 (2003, 4, 10, '$406,793.79'),
 (2003, 4, 11, '$939,511.52'),
 (2003, 4, 12, '$443,373.38'),
 (2004, 1, 1, '$256,314.74'),
 (2004, 1, 2, '$302,020.72'),
 (2004, 1, 3, '$202,394.82'),
 (2004, 2, 4, '$200,268.89'),
 (2004, 2, 5, '$233,036.00'),
 (2004, 2, 6, '$198,017.52'),
 (2004, 3, 7, '$386,081.97'),
 (2004, 3, 8, '$355,964.29'),
 (2004, 3, 9, '$306,754.74'),
 (2004, 4, 10, '$540,641.72'),
 (2004, 4, 11, '$956,277.81'),
 (2004, 4, 12, '$428,838.17'),
 (2005, 1, 1, '$260,966.50'),
 (2005, 1, 2, '$359,495.98'),
 (2005, 1, 3, '$351,746.35'),
 (2005, 2, 4, '$261,498.35'),
 (2005, 2, 5, '$255,396.57')]

__I have had about as much fun with dates and times as I can stand for one day.__

## IF, IFNULL

Consider revenue per customer for Classic Models.

In [28]:
%%sql

/*
    How many customers are there?
*/
select count(*) as no_of_customers from classicmodels.customers;

 * mysql+pymysql://root:***@localhost
1 rows affected.

[(122,)]

In [29]:
%%sql

with one as (
    select customerNumber, orderNumber, quantityOrdered*priceEach as revenue from orders join orderdetails using(orderNumber)
),
    two as (
        select customerNumber, sum(revenue) as total_revenue from one group by customerNumber
    )
select
    customerNumber,
    (select customerName from customers where customers.customerNumber=two.customerNumber) as customerName,
    total_revenue from two;

 * mysql+pymysql://root:***@localhost
98 rows affected.

[(103, 'Atelier graphique', Decimal('22314.36')),
 (112, 'Signal Gift Stores', Decimal('80180.98')),
 (114, 'Australian Collectors, Co.', Decimal('180585.07')),
 (119, 'La Rochelle Gifts', Decimal('158573.12')),
 (121, 'Baane Mini Imports', Decimal('104224.79')),
 (124, 'Mini Gifts Distributors Ltd.', Decimal('591827.34')),
 (128, 'Blauer See Auto, Co.', Decimal('75937.76')),
 (129, 'Mini Wheels Co.', Decimal('66710.56')),
 (131, 'Land of Toys Inc.', Decimal('149085.15')),
 (141, 'Euro+ Shopping Channel', Decimal('820689.54')),
 (144, 'Volvo Model Replicas, Co', Decimal('66694.82')),
 (145, 'Danish Wholesale Imports', Decimal('129085.12')),
 (146, 'Saveley & Henriot, Co.', Decimal('130305.35')),
 (148, 'Dragon Souveniers, Ltd.', Decimal('156251.03')),
 (151, 'Muscle Machine Inc', Decimal('177913.95')),
 (157, 'Diecast Classics Inc.', Decimal('104358.69')),
 (161, 'Technics Stores Inc.', Decimal('104545.22')),
 (166, 'Handji Gifts& Co', Decimal('107746.75')),
 (167, 'Herkku Gifts', Decimal('97562.47')),
 (171, 'Daedalus Designs Imports', Decimal('61781.70')),
 (172, "La Corne D'abondance, Co.", Decimal('86553.52')),
 (173, 'Cambridge Collectables Co.', Decimal('32198.69')),
 (175, 'Gift Depot Inc.', Decimal('95424.63')),
 (177, 'Osaka Souveniers Co.', Decimal('62361.22')),
 (181, 'Vitachrome Inc.', Decimal('72497.64')),
 (186, 'Toys of Finland, Co.', Decimal('95546.46')),
 (187, 'AV Stores, Co.', Decimal('148410.09')),
 (189, 'Clover Collections, Co.', Decimal('49898.27')),
 (198, 'Auto-Moto Classics Inc.', Decimal('21554.26')),
 (201, 'UK Collectables, Ltd.', Decimal('106610.72')),
 (202, 'Canadian Gift Exchange Network', Decimal('70122.19')),
 (204, 'Online Mini Collectables', Decimal('55577.26')),
 (205, 'Toys4GrownUps.com', Decimal('93803.30')),
 (209, 'Mini Caravy', Decimal('75859.32')),
 (211, 'King Kong Collectables, Co.', Decimal('45480.79')),
 (216, 'Enaco Distributors', Decimal('68520.47')),
 (219, 'Boards & Toys Co.', Decimal('7918.60')),
 (227, 'Heintze Collectables', Decimal('89909.80')),
 (233, 'Québec Home Shopping Network', Decimal('68977.67')),
 (239, 'Collectable Mini Designs Co.', Decimal('80375.24')),
 (240, 'giftsbymail.co.uk', Decimal('71783.75')),
 (242, 'Alpha Cognac', Decimal('60483.36')),
 (249, 'Amica Models & Co.', Decimal('82223.23')),
 (250, 'Lyon Souveniers', Decimal('67659.19')),
 (256, 'Auto Associés & Cie.', Decimal('58876.41')),
 (259, 'Toms Spezialitäten, Ltd', Decimal('89223.14')),
 (260, 'Royal Canadian Collectables, Ltd.', Decimal('66812.00')),
 (276, "Anna's Decorations, Ltd", Decimal('137034.22')),
 (278, 'Rovelli Gifts', Decimal('127529.69')),
 (282, 'Souveniers And Things Co.', Decimal('133907.12')),
 (286, "Marta's Replicas Co.", Decimal('90545.37')),
 (298, 'Vida Sport, Ltd', Decimal('108777.92')),
 (299, 'Norway Gifts By Mail, Co.', Decimal('69059.04')),
 (311, 'Oulu Toy Supplies, Inc.', Decimal('95706.15')),
 (314, 'Petit Auto', Decimal('70851.58')),
 (319, 'Mini Classics', Decimal('78432.16')),
 (320, 'Mini Creations Ltd.', Decimal('101872.52')),
 (321, 'Corporate Gift Ideas Co.', Decimal('132340.78')),
 (323, 'Down Under Souveniers, Inc', Decimal('154622.08')),
 (324, 'Stylish Desk Decors, Co.', Decimal('80556.73')),
 (328, 'Tekni Collectables Inc.', Decimal('81806.55')),
 (333, 'Australian Gift Network, Co', Decimal('55190.16')),
 (334, 'Suominen Souveniers', Decimal('103896.74')),
 (339, 'Classic Gift Ideas, Inc', Decimal('57939.34')),
 (344, 'CAF Imports', Decimal('46751.14')),
 (347, "Men 'R' US Retailers, Ltd.", Decimal('41506.19')),
 (350, 'Marseille Mini Autos', Decimal('71547.53')),
 (353, 'Reims Collectables', Decimal('126983.19')),
 (357, 'GiftsForHim.com', Decimal('94431.76')),
 (362, 'Gifts4AllAges.com', Decimal('84340.32')),
 (363, 'Online Diecast Creations Co.', Decimal('116449.29')),
 (379, 'Collectables For Less Inc.', Decimal('73533.65')),
 (381, 'Royale Belge', Decimal('29217.18')),
 (382, 'Salzburg Collectables', Decimal('137480.07')),
 (385, 'Cruz & Sons Co.', Decimal('87468.30')),
 (386, "L'ordine Souveniers", Decimal('125505.57')),
 (398, 'Tokyo Collectables, Ltd', Decimal('105548.73')),
 (406, 'Auto Canal+ Petit', Decimal('86436.97')),
 (412, 'Extreme Desk Decorations, Ltd', Decimal('90332.38')),
 (415, 'Bavarian Collectables Imports, Co.', Decimal('31310.09')),
 (424, 'Classic Legends Inc.', Decimal('69214.33')),
 (447, 'Gift Ideas Corp.', Decimal('49967.78')),
 (448, 'Scandinavian Gift Ideas', Decimal('120943.53')),
 (450, 'The Sharp Gifts Warehouse', Decimal('143536.27')),
 (452, 'Mini Auto Werke', Decimal('51059.99')),
 (455, 'Super Scale Inc.', Decimal('70378.65')),
 (456, 'Microscale Inc.', Decimal('29230.43')),
 (458, 'Corrida Auto Replicas, Ltd', Decimal('112440.09')),
 (462, 'FunGiftIdeas.com', Decimal('88627.49')),
 (471, 'Australian Collectables, Ltd', Decimal('55866.02')),
 (473, 'Frau da Collezione', Decimal('25358.32')),
 (475, 'West Coast Collectables Co.', Decimal('43748.72')),
 (484, 'Iberia Gift Imports, Corp.', Decimal('50987.85')),
 (486, 'Motor Mint Distributors Inc.', Decimal('77726.59')),
 (487, 'Signal Collectibles Ltd.', Decimal('42570.37')),
 (489, 'Double Decker Gift Stores, Ltd', Decimal('29586.15')),
 (495, 'Diecast Collectables', Decimal('65541.74')),
 (496, "Kelly's Gift Shop", Decimal('137460.79'))]

I have 98 entries but 122 customers. Clearly some are missing. Let's try a slightly different approach

In [30]:
%%sql

with one as (
    select customerNumber, orderNumber, quantityOrdered*priceEach as revenue from orders join orderdetails using(orderNumber)
),
    two as (
        select customerNumber, sum(revenue) as total_revenue from one group by customerNumber
    )
select
    customerNumber, customerName, total_revenue from customers left join two using(customerNumber)
    order by total_revenue;

 * mysql+pymysql://root:***@localhost
122 rows affected.

[(125, 'Havel & Zbyszek Co', None),
 (168, 'American Souvenirs Inc', None),
 (169, 'Porto Imports Co.', None),
 (206, 'Asian Shopping Network, Co', None),
 (223, 'Natürlich Autos', None),
 (237, 'ANG Resellers', None),
 (247, 'Messner Shopping Network', None),
 (273, 'Franken Gifts, Co', None),
 (293, 'BG&E Collectables', None),
 (303, 'Schuyler Imports', None),
 (307, 'Der Hund Imports', None),
 (335, 'Cramer Spezialitäten, Ltd', None),
 (348, 'Asian Treasures, Inc.', None),
 (356, 'SAR Distributors, Co', None),
 (361, 'Kommission Auto', None),
 (369, 'Lisboa Souveniers, Inc', None),
 (376, 'Precious Collectables', None),
 (409, 'Stuttgart Collectable Exchange', None),
 (443, 'Feuer Online Stores, Inc', None),
 (459, 'Warburg Exchange', None),
 (465, 'Anton Designs, Ltd.', None),
 (477, 'Mit Vergnügen & Co.', None),
 (480, 'Kremlin Collectables, Co.', None),
 (481, 'Raanan Stores, Inc', None),
 (219, 'Boards & Toys Co.', Decimal('7918.60')),
 (198, 'Auto-Moto Classics Inc.', Decimal('21554.26')),
 (103, 'Atelier graphique', Decimal('22314.36')),
 (473, 'Frau da Collezione', Decimal('25358.32')),
 (381, 'Royale Belge', Decimal('29217.18')),
 (456, 'Microscale Inc.', Decimal('29230.43')),
 (489, 'Double Decker Gift Stores, Ltd', Decimal('29586.15')),
 (415, 'Bavarian Collectables Imports, Co.', Decimal('31310.09')),
 (173, 'Cambridge Collectables Co.', Decimal('32198.69')),
 (347, "Men 'R' US Retailers, Ltd.", Decimal('41506.19')),
 (487, 'Signal Collectibles Ltd.', Decimal('42570.37')),
 (475, 'West Coast Collectables Co.', Decimal('43748.72')),
 (211, 'King Kong Collectables, Co.', Decimal('45480.79')),
 (344, 'CAF Imports', Decimal('46751.14')),
 (189, 'Clover Collections, Co.', Decimal('49898.27')),
 (447, 'Gift Ideas Corp.', Decimal('49967.78')),
 (484, 'Iberia Gift Imports, Corp.', Decimal('50987.85')),
 (452, 'Mini Auto Werke', Decimal('51059.99')),
 (333, 'Australian Gift Network, Co', Decimal('55190.16')),
 (204, 'Online Mini Collectables', Decimal('55577.26')),
 (471, 'Australian Collectables, Ltd', Decimal('55866.02')),
 (339, 'Classic Gift Ideas, Inc', Decimal('57939.34')),
 (256, 'Auto Associés & Cie.', Decimal('58876.41')),
 (242, 'Alpha Cognac', Decimal('60483.36')),
 (171, 'Daedalus Designs Imports', Decimal('61781.70')),
 (177, 'Osaka Souveniers Co.', Decimal('62361.22')),
 (495, 'Diecast Collectables', Decimal('65541.74')),
 (144, 'Volvo Model Replicas, Co', Decimal('66694.82')),
 (129, 'Mini Wheels Co.', Decimal('66710.56')),
 (260, 'Royal Canadian Collectables, Ltd.', Decimal('66812.00')),
 (250, 'Lyon Souveniers', Decimal('67659.19')),
 (216, 'Enaco Distributors', Decimal('68520.47')),
 (233, 'Québec Home Shopping Network', Decimal('68977.67')),
 (299, 'Norway Gifts By Mail, Co.', Decimal('69059.04')),
 (424, 'Classic Legends Inc.', Decimal('69214.33')),
 (202, 'Canadian Gift Exchange Network', Decimal('70122.19')),
 (455, 'Super Scale Inc.', Decimal('70378.65')),
 (314, 'Petit Auto', Decimal('70851.58')),
 (350, 'Marseille Mini Autos', Decimal('71547.53')),
 (240, 'giftsbymail.co.uk', Decimal('71783.75')),
 (181, 'Vitachrome Inc.', Decimal('72497.64')),
 (379, 'Collectables For Less Inc.', Decimal('73533.65')),
 (209, 'Mini Caravy', Decimal('75859.32')),
 (128, 'Blauer See Auto, Co.', Decimal('75937.76')),
 (486, 'Motor Mint Distributors Inc.', Decimal('77726.59')),
 (319, 'Mini Classics', Decimal('78432.16')),
 (112, 'Signal Gift Stores', Decimal('80180.98')),
 (239, 'Collectable Mini Designs Co.', Decimal('80375.24')),
 (324, 'Stylish Desk Decors, Co.', Decimal('80556.73')),
 (328, 'Tekni Collectables Inc.', Decimal('81806.55')),
 (249, 'Amica Models & Co.', Decimal('82223.23')),
 (362, 'Gifts4AllAges.com', Decimal('84340.32')),
 (406, 'Auto Canal+ Petit', Decimal('86436.97')),
 (172, "La Corne D'abondance, Co.", Decimal('86553.52')),
 (385, 'Cruz & Sons Co.', Decimal('87468.30')),
 (462, 'FunGiftIdeas.com', Decimal('88627.49')),
 (259, 'Toms Spezialitäten, Ltd', Decimal('89223.14')),
 (227, 'Heintze Collectables', Decimal('89909.80')),
 (412, 'Extreme Desk Decorations, Ltd', Decimal('90332.38')),
 (286, "Marta's Replicas Co.", Decimal('90545.37')),
 (205, 'Toys4GrownUps.com', Decimal('93803.30')),
 (357, 'GiftsForHim.com', Decimal('94431.76')),
 (175, 'Gift Depot Inc.', Decimal('95424.63')),
 (186, 'Toys of Finland, Co.', Decimal('95546.46')),
 (311, 'Oulu Toy Supplies, Inc.', Decimal('95706.15')),
 (167, 'Herkku Gifts', Decimal('97562.47')),
 (320, 'Mini Creations Ltd.', Decimal('101872.52')),
 (334, 'Suominen Souveniers', Decimal('103896.74')),
 (121, 'Baane Mini Imports', Decimal('104224.79')),
 (157, 'Diecast Classics Inc.', Decimal('104358.69')),
 (161, 'Technics Stores Inc.', Decimal('104545.22')),
 (398, 'Tokyo Collectables, Ltd', Decimal('105548.73')),
 (201, 'UK Collectables, Ltd.', Decimal('106610.72')),
 (166, 'Handji Gifts& Co', Decimal('107746.75')),
 (298, 'Vida Sport, Ltd', Decimal('108777.92')),
 (458, 'Corrida Auto Replicas, Ltd', Decimal('112440.09')),
 (363, 'Online Diecast Creations Co.', Decimal('116449.29')),
 (448, 'Scandinavian Gift Ideas', Decimal('120943.53')),
 (386, "L'ordine Souveniers", Decimal('125505.57')),
 (353, 'Reims Collectables', Decimal('126983.19')),
 (278, 'Rovelli Gifts', Decimal('127529.69')),
 (145, 'Danish Wholesale Imports', Decimal('129085.12')),
 (146, 'Saveley & Henriot, Co.', Decimal('130305.35')),
 (321, 'Corporate Gift Ideas Co.', Decimal('132340.78')),
 (282, 'Souveniers And Things Co.', Decimal('133907.12')),
 (276, "Anna's Decorations, Ltd", Decimal('137034.22')),
 (496, "Kelly's Gift Shop", Decimal('137460.79')),
 (382, 'Salzburg Collectables', Decimal('137480.07')),
 (450, 'The Sharp Gifts Warehouse', Decimal('143536.27')),
 (187, 'AV Stores, Co.', Decimal('148410.09')),
 (131, 'Land of Toys Inc.', Decimal('149085.15')),
 (323, 'Down Under Souveniers, Inc', Decimal('154622.08')),
 (148, 'Dragon Souveniers, Ltd.', Decimal('156251.03')),
 (119, 'La Rochelle Gifts', Decimal('158573.12')),
 (151, 'Muscle Machine Inc', Decimal('177913.95')),
 (114, 'Australian Collectors, Co.', Decimal('180585.07')),
 (124, 'Mini Gifts Distributors Ltd.', Decimal('591827.34')),
 (141, 'Euro+ Shopping Channel', Decimal('820689.54'))]

Well, ```NULL``` maps to ```None``` in Python, but we know the answer. It is ```0```.

In [31]:
%%sql

with one as (
    select customerNumber, orderNumber, quantityOrdered*priceEach as revenue from orders join orderdetails using(orderNumber)
),
    two as (
        select customerNumber, sum(revenue) as total_revenue from one group by customerNumber
    )
select
    customerNumber, customerName, ifnull(total_revenue,0) as total_revenue from customers left join two using(customerNumber)
    order by total_revenue;

 * mysql+pymysql://root:***@localhost
122 rows affected.

[(125, 'Havel & Zbyszek Co', Decimal('0.00')),
 (168, 'American Souvenirs Inc', Decimal('0.00')),
 (169, 'Porto Imports Co.', Decimal('0.00')),
 (206, 'Asian Shopping Network, Co', Decimal('0.00')),
 (223, 'Natürlich Autos', Decimal('0.00')),
 (237, 'ANG Resellers', Decimal('0.00')),
 (247, 'Messner Shopping Network', Decimal('0.00')),
 (273, 'Franken Gifts, Co', Decimal('0.00')),
 (293, 'BG&E Collectables', Decimal('0.00')),
 (303, 'Schuyler Imports', Decimal('0.00')),
 (307, 'Der Hund Imports', Decimal('0.00')),
 (335, 'Cramer Spezialitäten, Ltd', Decimal('0.00')),
 (348, 'Asian Treasures, Inc.', Decimal('0.00')),
 (356, 'SAR Distributors, Co', Decimal('0.00')),
 (361, 'Kommission Auto', Decimal('0.00')),
 (369, 'Lisboa Souveniers, Inc', Decimal('0.00')),
 (376, 'Precious Collectables', Decimal('0.00')),
 (409, 'Stuttgart Collectable Exchange', Decimal('0.00')),
 (443, 'Feuer Online Stores, Inc', Decimal('0.00')),
 (459, 'Warburg Exchange', Decimal('0.00')),
 (465, 'Anton Designs, Ltd.', Decimal('0.00')),
 (477, 'Mit Vergnügen & Co.', Decimal('0.00')),
 (480, 'Kremlin Collectables, Co.', Decimal('0.00')),
 (481, 'Raanan Stores, Inc', Decimal('0.00')),
 (219, 'Boards & Toys Co.', Decimal('7918.60')),
 (198, 'Auto-Moto Classics Inc.', Decimal('21554.26')),
 (103, 'Atelier graphique', Decimal('22314.36')),
 (473, 'Frau da Collezione', Decimal('25358.32')),
 (381, 'Royale Belge', Decimal('29217.18')),
 (456, 'Microscale Inc.', Decimal('29230.43')),
 (489, 'Double Decker Gift Stores, Ltd', Decimal('29586.15')),
 (415, 'Bavarian Collectables Imports, Co.', Decimal('31310.09')),
 (173, 'Cambridge Collectables Co.', Decimal('32198.69')),
 (347, "Men 'R' US Retailers, Ltd.", Decimal('41506.19')),
 (487, 'Signal Collectibles Ltd.', Decimal('42570.37')),
 (475, 'West Coast Collectables Co.', Decimal('43748.72')),
 (211, 'King Kong Collectables, Co.', Decimal('45480.79')),
 (344, 'CAF Imports', Decimal('46751.14')),
 (189, 'Clover Collections, Co.', Decimal('49898.27')),
 (447, 'Gift Ideas Corp.', Decimal('49967.78')),
 (484, 'Iberia Gift Imports, Corp.', Decimal('50987.85')),
 (452, 'Mini Auto Werke', Decimal('51059.99')),
 (333, 'Australian Gift Network, Co', Decimal('55190.16')),
 (204, 'Online Mini Collectables', Decimal('55577.26')),
 (471, 'Australian Collectables, Ltd', Decimal('55866.02')),
 (339, 'Classic Gift Ideas, Inc', Decimal('57939.34')),
 (256, 'Auto Associés & Cie.', Decimal('58876.41')),
 (242, 'Alpha Cognac', Decimal('60483.36')),
 (171, 'Daedalus Designs Imports', Decimal('61781.70')),
 (177, 'Osaka Souveniers Co.', Decimal('62361.22')),
 (495, 'Diecast Collectables', Decimal('65541.74')),
 (144, 'Volvo Model Replicas, Co', Decimal('66694.82')),
 (129, 'Mini Wheels Co.', Decimal('66710.56')),
 (260, 'Royal Canadian Collectables, Ltd.', Decimal('66812.00')),
 (250, 'Lyon Souveniers', Decimal('67659.19')),
 (216, 'Enaco Distributors', Decimal('68520.47')),
 (233, 'Québec Home Shopping Network', Decimal('68977.67')),
 (299, 'Norway Gifts By Mail, Co.', Decimal('69059.04')),
 (424, 'Classic Legends Inc.', Decimal('69214.33')),
 (202, 'Canadian Gift Exchange Network', Decimal('70122.19')),
 (455, 'Super Scale Inc.', Decimal('70378.65')),
 (314, 'Petit Auto', Decimal('70851.58')),
 (350, 'Marseille Mini Autos', Decimal('71547.53')),
 (240, 'giftsbymail.co.uk', Decimal('71783.75')),
 (181, 'Vitachrome Inc.', Decimal('72497.64')),
 (379, 'Collectables For Less Inc.', Decimal('73533.65')),
 (209, 'Mini Caravy', Decimal('75859.32')),
 (128, 'Blauer See Auto, Co.', Decimal('75937.76')),
 (486, 'Motor Mint Distributors Inc.', Decimal('77726.59')),
 (319, 'Mini Classics', Decimal('78432.16')),
 (112, 'Signal Gift Stores', Decimal('80180.98')),
 (239, 'Collectable Mini Designs Co.', Decimal('80375.24')),
 (324, 'Stylish Desk Decors, Co.', Decimal('80556.73')),
 (328, 'Tekni Collectables Inc.', Decimal('81806.55')),
 (249, 'Amica Models & Co.', Decimal('82223.23')),
 (362, 'Gifts4AllAges.com', Decimal('84340.32')),
 (406, 'Auto Canal+ Petit', Decimal('86436.97')),
 (172, "La Corne D'abondance, Co.", Decimal('86553.52')),
 (385, 'Cruz & Sons Co.', Decimal('87468.30')),
 (462, 'FunGiftIdeas.com', Decimal('88627.49')),
 (259, 'Toms Spezialitäten, Ltd', Decimal('89223.14')),
 (227, 'Heintze Collectables', Decimal('89909.80')),
 (412, 'Extreme Desk Decorations, Ltd', Decimal('90332.38')),
 (286, "Marta's Replicas Co.", Decimal('90545.37')),
 (205, 'Toys4GrownUps.com', Decimal('93803.30')),
 (357, 'GiftsForHim.com', Decimal('94431.76')),
 (175, 'Gift Depot Inc.', Decimal('95424.63')),
 (186, 'Toys of Finland, Co.', Decimal('95546.46')),
 (311, 'Oulu Toy Supplies, Inc.', Decimal('95706.15')),
 (167, 'Herkku Gifts', Decimal('97562.47')),
 (320, 'Mini Creations Ltd.', Decimal('101872.52')),
 (334, 'Suominen Souveniers', Decimal('103896.74')),
 (121, 'Baane Mini Imports', Decimal('104224.79')),
 (157, 'Diecast Classics Inc.', Decimal('104358.69')),
 (161, 'Technics Stores Inc.', Decimal('104545.22')),
 (398, 'Tokyo Collectables, Ltd', Decimal('105548.73')),
 (201, 'UK Collectables, Ltd.', Decimal('106610.72')),
 (166, 'Handji Gifts& Co', Decimal('107746.75')),
 (298, 'Vida Sport, Ltd', Decimal('108777.92')),
 (458, 'Corrida Auto Replicas, Ltd', Decimal('112440.09')),
 (363, 'Online Diecast Creations Co.', Decimal('116449.29')),
 (448, 'Scandinavian Gift Ideas', Decimal('120943.53')),
 (386, "L'ordine Souveniers", Decimal('125505.57')),
 (353, 'Reims Collectables', Decimal('126983.19')),
 (278, 'Rovelli Gifts', Decimal('127529.69')),
 (145, 'Danish Wholesale Imports', Decimal('129085.12')),
 (146, 'Saveley & Henriot, Co.', Decimal('130305.35')),
 (321, 'Corporate Gift Ideas Co.', Decimal('132340.78')),
 (282, 'Souveniers And Things Co.', Decimal('133907.12')),
 (276, "Anna's Decorations, Ltd", Decimal('137034.22')),
 (496, "Kelly's Gift Shop", Decimal('137460.79')),
 (382, 'Salzburg Collectables', Decimal('137480.07')),
 (450, 'The Sharp Gifts Warehouse', Decimal('143536.27')),
 (187, 'AV Stores, Co.', Decimal('148410.09')),
 (131, 'Land of Toys Inc.', Decimal('149085.15')),
 (323, 'Down Under Souveniers, Inc', Decimal('154622.08')),
 (148, 'Dragon Souveniers, Ltd.', Decimal('156251.03')),
 (119, 'La Rochelle Gifts', Decimal('158573.12')),
 (151, 'Muscle Machine Inc', Decimal('177913.95')),
 (114, 'Australian Collectors, Co.', Decimal('180585.07')),
 (124, 'Mini Gifts Distributors Ltd.', Decimal('591827.34')),
 (141, 'Euro+ Shopping Channel', Decimal('820689.54'))]

This example of ```IF``` is a little contrived, but it does show the behavior.

Also, note that I had to use a subquery to get the average. I could not just call ```avg```.

In [32]:
%%sql

with one as (
    select customerNumber, orderNumber, quantityOrdered*priceEach as revenue from orders join orderdetails using(orderNumber)
),
    two as (
        select customerNumber, sum(revenue) as total_revenue from one group by customerNumber
    ),
three as (
    select
    customerNumber, customerName, ifnull(total_revenue, 0) as total_revenue from customers left join two using (customerNumber)
    order by total_revenue
    )
select
    customerNumber, customerName, total_revenue,
        if(total_revenue >= (select avg(total_revenue) from three), "Good Customer", "Bad Customer") customer_kind
from
    three;

 * mysql+pymysql://root:***@localhost
122 rows affected.

[(125, 'Havel & Zbyszek Co', Decimal('0.00'), 'Bad Customer'),
 (168, 'American Souvenirs Inc', Decimal('0.00'), 'Bad Customer'),
 (169, 'Porto Imports Co.', Decimal('0.00'), 'Bad Customer'),
 (206, 'Asian Shopping Network, Co', Decimal('0.00'), 'Bad Customer'),
 (223, 'Natürlich Autos', Decimal('0.00'), 'Bad Customer'),
 (237, 'ANG Resellers', Decimal('0.00'), 'Bad Customer'),
 (247, 'Messner Shopping Network', Decimal('0.00'), 'Bad Customer'),
 (273, 'Franken Gifts, Co', Decimal('0.00'), 'Bad Customer'),
 (293, 'BG&E Collectables', Decimal('0.00'), 'Bad Customer'),
 (303, 'Schuyler Imports', Decimal('0.00'), 'Bad Customer'),
 (307, 'Der Hund Imports', Decimal('0.00'), 'Bad Customer'),
 (335, 'Cramer Spezialitäten, Ltd', Decimal('0.00'), 'Bad Customer'),
 (348, 'Asian Treasures, Inc.', Decimal('0.00'), 'Bad Customer'),
 (356, 'SAR Distributors, Co', Decimal('0.00'), 'Bad Customer'),
 (361, 'Kommission Auto', Decimal('0.00'), 'Bad Customer'),
 (369, 'Lisboa Souveniers, Inc', Decimal('0.00'), 'Bad Customer'),
 (376, 'Precious Collectables', Decimal('0.00'), 'Bad Customer'),
 (409, 'Stuttgart Collectable Exchange', Decimal('0.00'), 'Bad Customer'),
 (443, 'Feuer Online Stores, Inc', Decimal('0.00'), 'Bad Customer'),
 (459, 'Warburg Exchange', Decimal('0.00'), 'Bad Customer'),
 (465, 'Anton Designs, Ltd.', Decimal('0.00'), 'Bad Customer'),
 (477, 'Mit Vergnügen & Co.', Decimal('0.00'), 'Bad Customer'),
 (480, 'Kremlin Collectables, Co.', Decimal('0.00'), 'Bad Customer'),
 (481, 'Raanan Stores, Inc', Decimal('0.00'), 'Bad Customer'),
 (219, 'Boards & Toys Co.', Decimal('7918.60'), 'Bad Customer'),
 (198, 'Auto-Moto Classics Inc.', Decimal('21554.26'), 'Bad Customer'),
 (103, 'Atelier graphique', Decimal('22314.36'), 'Bad Customer'),
 (473, 'Frau da Collezione', Decimal('25358.32'), 'Bad Customer'),
 (381, 'Royale Belge', Decimal('29217.18'), 'Bad Customer'),
 (456, 'Microscale Inc.', Decimal('29230.43'), 'Bad Customer'),
 (489, 'Double Decker Gift Stores, Ltd', Decimal('29586.15'), 'Bad Customer'),
 (415, 'Bavarian Collectables Imports, Co.', Decimal('31310.09'), 'Bad Customer'),
 (173, 'Cambridge Collectables Co.', Decimal('32198.69'), 'Bad Customer'),
 (347, "Men 'R' US Retailers, Ltd.", Decimal('41506.19'), 'Bad Customer'),
 (487, 'Signal Collectibles Ltd.', Decimal('42570.37'), 'Bad Customer'),
 (475, 'West Coast Collectables Co.', Decimal('43748.72'), 'Bad Customer'),
 (211, 'King Kong Collectables, Co.', Decimal('45480.79'), 'Bad Customer'),
 (344, 'CAF Imports', Decimal('46751.14'), 'Bad Customer'),
 (189, 'Clover Collections, Co.', Decimal('49898.27'), 'Bad Customer'),
 (447, 'Gift Ideas Corp.', Decimal('49967.78'), 'Bad Customer'),
 (484, 'Iberia Gift Imports, Corp.', Decimal('50987.85'), 'Bad Customer'),
 (452, 'Mini Auto Werke', Decimal('51059.99'), 'Bad Customer'),
 (333, 'Australian Gift Network, Co', Decimal('55190.16'), 'Bad Customer'),
 (204, 'Online Mini Collectables', Decimal('55577.26'), 'Bad Customer'),
 (471, 'Australian Collectables, Ltd', Decimal('55866.02'), 'Bad Customer'),
 (339, 'Classic Gift Ideas, Inc', Decimal('57939.34'), 'Bad Customer'),
 (256, 'Auto Associés & Cie.', Decimal('58876.41'), 'Bad Customer'),
 (242, 'Alpha Cognac', Decimal('60483.36'), 'Bad Customer'),
 (171, 'Daedalus Designs Imports', Decimal('61781.70'), 'Bad Customer'),
 (177, 'Osaka Souveniers Co.', Decimal('62361.22'), 'Bad Customer'),
 (495, 'Diecast Collectables', Decimal('65541.74'), 'Bad Customer'),
 (144, 'Volvo Model Replicas, Co', Decimal('66694.82'), 'Bad Customer'),
 (129, 'Mini Wheels Co.', Decimal('66710.56'), 'Bad Customer'),
 (260, 'Royal Canadian Collectables, Ltd.', Decimal('66812.00'), 'Bad Customer'),
 (250, 'Lyon Souveniers', Decimal('67659.19'), 'Bad Customer'),
 (216, 'Enaco Distributors', Decimal('68520.47'), 'Bad Customer'),
 (233, 'Québec Home Shopping Network', Decimal('68977.67'), 'Bad Customer'),
 (299, 'Norway Gifts By Mail, Co.', Decimal('69059.04'), 'Bad Customer'),
 (424, 'Classic Legends Inc.', Decimal('69214.33'), 'Bad Customer'),
 (202, 'Canadian Gift Exchange Network', Decimal('70122.19'), 'Bad Customer'),
 (455, 'Super Scale Inc.', Decimal('70378.65'), 'Bad Customer'),
 (314, 'Petit Auto', Decimal('70851.58'), 'Bad Customer'),
 (350, 'Marseille Mini Autos', Decimal('71547.53'), 'Bad Customer'),
 (240, 'giftsbymail.co.uk', Decimal('71783.75'), 'Bad Customer'),
 (181, 'Vitachrome Inc.', Decimal('72497.64'), 'Bad Customer'),
 (379, 'Collectables For Less Inc.', Decimal('73533.65'), 'Bad Customer'),
 (209, 'Mini Caravy', Decimal('75859.32'), 'Bad Customer'),
 (128, 'Blauer See Auto, Co.', Decimal('75937.76'), 'Bad Customer'),
 (486, 'Motor Mint Distributors Inc.', Decimal('77726.59'), 'Bad Customer'),
 (319, 'Mini Classics', Decimal('78432.16'), 'Bad Customer'),
 (112, 'Signal Gift Stores', Decimal('80180.98'), 'Good Customer'),
 (239, 'Collectable Mini Designs Co.', Decimal('80375.24'), 'Good Customer'),
 (324, 'Stylish Desk Decors, Co.', Decimal('80556.73'), 'Good Customer'),
 (328, 'Tekni Collectables Inc.', Decimal('81806.55'), 'Good Customer'),
 (249, 'Amica Models & Co.', Decimal('82223.23'), 'Good Customer'),
 (362, 'Gifts4AllAges.com', Decimal('84340.32'), 'Good Customer'),
 (406, 'Auto Canal+ Petit', Decimal('86436.97'), 'Good Customer'),
 (172, "La Corne D'abondance, Co.", Decimal('86553.52'), 'Good Customer'),
 (385, 'Cruz & Sons Co.', Decimal('87468.30'), 'Good Customer'),
 (462, 'FunGiftIdeas.com', Decimal('88627.49'), 'Good Customer'),
 (259, 'Toms Spezialitäten, Ltd', Decimal('89223.14'), 'Good Customer'),
 (227, 'Heintze Collectables', Decimal('89909.80'), 'Good Customer'),
 (412, 'Extreme Desk Decorations, Ltd', Decimal('90332.38'), 'Good Customer'),
 (286, "Marta's Replicas Co.", Decimal('90545.37'), 'Good Customer'),
 (205, 'Toys4GrownUps.com', Decimal('93803.30'), 'Good Customer'),
 (357, 'GiftsForHim.com', Decimal('94431.76'), 'Good Customer'),
 (175, 'Gift Depot Inc.', Decimal('95424.63'), 'Good Customer'),
 (186, 'Toys of Finland, Co.', Decimal('95546.46'), 'Good Customer'),
 (311, 'Oulu Toy Supplies, Inc.', Decimal('95706.15'), 'Good Customer'),
 (167, 'Herkku Gifts', Decimal('97562.47'), 'Good Customer'),
 (320, 'Mini Creations Ltd.', Decimal('101872.52'), 'Good Customer'),
 (334, 'Suominen Souveniers', Decimal('103896.74'), 'Good Customer'),
 (121, 'Baane Mini Imports', Decimal('104224.79'), 'Good Customer'),
 (157, 'Diecast Classics Inc.', Decimal('104358.69'), 'Good Customer'),
 (161, 'Technics Stores Inc.', Decimal('104545.22'), 'Good Customer'),
 (398, 'Tokyo Collectables, Ltd', Decimal('105548.73'), 'Good Customer'),
 (201, 'UK Collectables, Ltd.', Decimal('106610.72'), 'Good Customer'),
 (166, 'Handji Gifts& Co', Decimal('107746.75'), 'Good Customer'),
 (298, 'Vida Sport, Ltd', Decimal('108777.92'), 'Good Customer'),
 (458, 'Corrida Auto Replicas, Ltd', Decimal('112440.09'), 'Good Customer'),
 (363, 'Online Diecast Creations Co.', Decimal('116449.29'), 'Good Customer'),
 (448, 'Scandinavian Gift Ideas', Decimal('120943.53'), 'Good Customer'),
 (386, "L'ordine Souveniers", Decimal('125505.57'), 'Good Customer'),
 (353, 'Reims Collectables', Decimal('126983.19'), 'Good Customer'),
 (278, 'Rovelli Gifts', Decimal('127529.69'), 'Good Customer'),
 (145, 'Danish Wholesale Imports', Decimal('129085.12'), 'Good Customer'),
 (146, 'Saveley & Henriot, Co.', Decimal('130305.35'), 'Good Customer'),
 (321, 'Corporate Gift Ideas Co.', Decimal('132340.78'), 'Good Customer'),
 (282, 'Souveniers And Things Co.', Decimal('133907.12'), 'Good Customer'),
 (276, "Anna's Decorations, Ltd", Decimal('137034.22'), 'Good Customer'),
 (496, "Kelly's Gift Shop", Decimal('137460.79'), 'Good Customer'),
 (382, 'Salzburg Collectables', Decimal('137480.07'), 'Good Customer'),
 (450, 'The Sharp Gifts Warehouse', Decimal('143536.27'), 'Good Customer'),
 (187, 'AV Stores, Co.', Decimal('148410.09'), 'Good Customer'),
 (131, 'Land of Toys Inc.', Decimal('149085.15'), 'Good Customer'),
 (323, 'Down Under Souveniers, Inc', Decimal('154622.08'), 'Good Customer'),
 (148, 'Dragon Souveniers, Ltd.', Decimal('156251.03'), 'Good Customer'),
 (119, 'La Rochelle Gifts', Decimal('158573.12'), 'Good Customer'),
 (151, 'Muscle Machine Inc', Decimal('177913.95'), 'Good Customer'),
 (114, 'Australian Collectors, Co.', Decimal('180585.07'), 'Good Customer'),
 (124, 'Mini Gifts Distributors Ltd.', Decimal('591827.34'), 'Good Customer'),
 (141, 'Euro+ Shopping Channel', Decimal('820689.54'), 'Good Customer')]

## Type Conversion

There are two basic, nearly the same, functions:
1. ```CAST()```
2. ```CONVERT()```

I have found them do be useful mostly when dealing with importing data from files, e.g. CSV, JSON.

In [35]:
players = [
    {
        "playerID": "gehrilo01",
        "nameFirst": "Lou",
        "nameLast": "Gehrig",
        "birthYear": 1903,
        "birthCountry": "USA",
        "bats": "L",
        "throws": "L",
        "weight": 200.0
    },
    {
        "playerID": "willite01",
        "nameFirst": "Ted",
        "nameLast": "Williams",
        "birthYear": 1918,
        "birthCountry": "USA",
        "bats": "L",
        "throws": "R",
        "weight": 205.0
    },
    {
        "playerID": "mantlmi01",
        "nameFirst": "Mickey",
        "nameLast": "Mantle",
        "birthYear": 1931,
        "birthCountry": "USA",
        "bats": "B",
        "throws": "R",
        "weight": 195.0
    },
    {
        "playerID": "robinja02",
        "nameFirst": "Jackie",
        "nameLast": "Robinson",
        "birthYear": 1919,
        "birthCountry": "USA",
        "bats": "R",
        "throws": "R",
        "weight": 195.0
    },
    {
        "playerID": "dimagjo01",
        "nameFirst": "Joe",
        "nameLast": "DiMaggio",
        "birthYear": 1914,
        "birthCountry": "USA",
        "bats": "R",
        "throws": "R",
        "weight": 193.0
    },
    {
        "playerID": "musialst01",
        "nameFirst": "Stan",
        "nameLast": "Musial",
        "birthYear": 1920,
        "birthCountry": "USA",
        "bats": "L",
        "throws": "L",
        "weight": 175.0
    },
    {
        "playerID": "koufasa01",
        "nameFirst": "Sandy",
        "nameLast": "Koufax",
        "birthYear": 1935,
        "birthCountry": "USA",
        "bats": "L",
        "throws": "L",
        "weight": 210.0
    },
    {
        "playerID": "jeterde01",
        "nameFirst": "Derek",
        "nameLast": "Jeter",
        "birthYear": 1974,
        "birthCountry": "USA",
        "bats": "R",
        "throws": "R",
        "weight": 195.0
    },
    {
        "playerID": "pujolal01",
        "nameFirst": "Albert",
        "nameLast": "Pujols",
        "birthYear": 1980,
        "birthCountry": "Dominican Republic",
        "bats": "R",
        "throws": "R",
        "weight": 230.0
    },
    {
        "playerID": "troutmi01",
        "nameFirst": "Mike",
        "nameLast": "Trout",
        "birthYear": 1991,
        "birthCountry": "USA",
        "bats": "R",
        "throws": "R",
        "weight": 235.0
    },
    {
        "playerID": "ohtansh01",
        "nameFirst": "Shohei",
        "nameLast": "Ohtani",
        "birthYear": 1994,
        "birthCountry": "Japan",
        "bats": "L",
        "throws": "R",
        "weight": 210.0
    }
]

In [36]:
df = pandas.DataFrame(players)
df

,playerID,nameFirst,nameLast,birthYear,birthCountry,bats,throws,weight
0,gehrilo01,Lou,Gehrig,1903,USA,L,L,200.0
1,willite01,Ted,Williams,1918,USA,L,R,205.0
2,mantlmi01,Mickey,Mantle,1931,USA,B,R,195.0
3,robinja02,Jackie,Robinson,1919,USA,R,R,195.0
4,dimagjo01,Joe,DiMaggio,1914,USA,R,R,193.0
5,musialst01,Stan,Musial,1920,USA,L,L,175.0
6,koufasa01,Sandy,Koufax,1935,USA,L,L,210.0
7,jeterde01,Derek,Jeter,1974,USA,R,R,195.0
8,pujolal01,Albert,Pujols,1980,Dominican Republic,R,R,230.0
9,troutmi01,Mike,Trout,1991,USA,R,R,235.0
10,ohtansh01,Shohei,Ohtani,1994,Japan,L,R,210.0

In [37]:
df.to_sql(
    "Simple_Players",
    schema="f2025_w4111_examples",
    index=False,
    if_exists="replace",
    con=engine
)

11

In [38]:
%sql use f2025_w4111_examples;

 * mysql+pymysql://root:***@localhost
0 rows affected.

[]

In [39]:
%sql describe Simple_players;

 * mysql+pymysql://root:***@localhost
8 rows affected.

[('playerID', 'text', 'YES', '', None, ''),
 ('nameFirst', 'text', 'YES', '', None, ''),
 ('nameLast', 'text', 'YES', '', None, ''),
 ('birthYear', 'bigint', 'YES', '', None, ''),
 ('birthCountry', 'text', 'YES', '', None, ''),
 ('bats', 'text', 'YES', '', None, ''),
 ('throws', 'text', 'YES', '', None, ''),
 ('weight', 'double', 'YES', '', None, '')]

Pandas and other import tools "guess" the data types from the values in the file. The tools often gues wrong. Guessing that
- An int column is double.
- A year is an int
  
are common examples. There are others.

In [40]:
%%sql

drop table if exists Simple_Players_Fixed;

create table Simple_Players_Fixed as 
select
    playerID, nameFirst, nameLast,
    cast(birthYear as Year) as birthYear,
    birthCountry,
    bats, throws,
    cast(weight as signed int) as weight
from
    Simple_players;

 * mysql+pymysql://root:***@localhost
0 rows affected.
11 rows affected.

[]

In [41]:
%sql describe Simple_Players_Fixed;

 * mysql+pymysql://root:***@localhost
8 rows affected.

[('playerID', 'text', 'YES', '', None, ''),
 ('nameFirst', 'text', 'YES', '', None, ''),
 ('nameLast', 'text', 'YES', '', None, ''),
 ('birthYear', 'year', 'YES', '', None, ''),
 ('birthCountry', 'text', 'YES', '', None, ''),
 ('bats', 'text', 'YES', '', None, ''),
 ('throws', 'text', 'YES', '', None, ''),
 ('weight', 'bigint', 'YES', '', None, '')]

Note that in a lot of cases, e.g. INSERT into a table, the database engine tries to automatical CAST/CONVERT the type.

In [42]:
%%sql

select playerID,
        birthYear+12.7 as funnyNumber,
        concat(weight, " is how much the players weighs") as funnyWeight,
        concat(birthYear, " plus ", weight, " plus 12.7 is ", birthYear+weight+12.7) as reallyWeird
from Simple_Players_Fixed;

 * mysql+pymysql://root:***@localhost
11 rows affected.

[('gehrilo01', Decimal('1915.7'), '200 is how much the players weighs', '1903 plus 200 plus 12.7 is 2115.7'),
 ('willite01', Decimal('1930.7'), '205 is how much the players weighs', '1918 plus 205 plus 12.7 is 2135.7'),
 ('mantlmi01', Decimal('1943.7'), '195 is how much the players weighs', '1931 plus 195 plus 12.7 is 2138.7'),
 ('robinja02', Decimal('1931.7'), '195 is how much the players weighs', '1919 plus 195 plus 12.7 is 2126.7'),
 ('dimagjo01', Decimal('1926.7'), '193 is how much the players weighs', '1914 plus 193 plus 12.7 is 2119.7'),
 ('musialst01', Decimal('1932.7'), '175 is how much the players weighs', '1920 plus 175 plus 12.7 is 2107.7'),
 ('koufasa01', Decimal('1947.7'), '210 is how much the players weighs', '1935 plus 210 plus 12.7 is 2157.7'),
 ('jeterde01', Decimal('1986.7'), '195 is how much the players weighs', '1974 plus 195 plus 12.7 is 2181.7'),
 ('pujolal01', Decimal('1992.7'), '230 is how much the players weighs', '1980 plus 230 plus 12.7 is 2222.7'),
 ('troutmi01', Decimal('2003.7'), '235 is how much the players weighs', '1991 plus 235 plus 12.7 is 2238.7'),
 ('ohtansh01', Decimal('2006.7'), '210 is how much the players weighs', '1994 plus 210 plus 12.7 is 2216.7')]

# Some More Fun with Strings

In [43]:
title_basics_df = pandas.read_csv("got_imdb_title_basics.csv")

In [44]:
title_basics_df.head(10)

,tconst,title_type,primary_title,alternate_title,is_adult,start_year,end_year,run_time_minutes,genres
0,tt0054518,tvSeries,The Avengers,The Avengers,0,1961.0,1969.0,50.0,"Action,Comedy,Crime"
1,tt0054571,tvSeries,Three Live Wires,Three Live Wires,0,1961.0,NaN,30.0,Comedy
2,tt0055556,movie,"Two Living, One Dead","Two Living, One Dead",0,1961.0,NaN,105.0,"Crime,Drama,Thriller"
3,tt0056105,movie,The Swingin' Maiden,The Iron Maiden,0,1962.0,NaN,98.0,"Comedy,Romance"
4,tt0056696,movie,Young and Willing,The Wild and the Willing,0,1962.0,NaN,110.0,"Drama,Romance"
5,tt0057435,movie,The Punch and Judy Man,The Punch and Judy Man,0,1963.0,NaN,96.0,Comedy
6,tt0058142,movie,Girl with Green Eyes,Girl with Green Eyes,0,1964.0,NaN,91.0,"Drama,Romance"
7,tt0058596,movie,Smokescreen,Smokescreen,0,1964.0,NaN,70.0,"Crime,Drama,Mystery"
8,tt0059106,movie,Die! Die! My Darling!,Fanatic,0,1965.0,NaN,97.0,"Horror,Thriller"
9,tt0059191,tvEpisode,For the West,For the West,0,1965.0,NaN,75.0,Drama

In [45]:
title_basics_df.to_sql(
    "title_basics_raw", schema="f2025_w4111_examples", con=engine, index=False, if_exists="replace"
)

29058

In [46]:
%sql select * from title_basics_raw limit 10

 * mysql+pymysql://root:***@localhost
10 rows affected.

[('tt0054518', 'tvSeries', 'The Avengers', 'The Avengers', 0, 1961.0, 1969.0, 50.0, 'Action,Comedy,Crime'),
 ('tt0054571', 'tvSeries', 'Three Live Wires', 'Three Live Wires', 0, 1961.0, None, 30.0, 'Comedy'),
 ('tt0055556', 'movie', 'Two Living, One Dead', 'Two Living, One Dead', 0, 1961.0, None, 105.0, 'Crime,Drama,Thriller'),
 ('tt0056105', 'movie', "The Swingin' Maiden", 'The Iron Maiden', 0, 1962.0, None, 98.0, 'Comedy,Romance'),
 ('tt0056696', 'movie', 'Young and Willing', 'The Wild and the Willing', 0, 1962.0, None, 110.0, 'Drama,Romance'),
 ('tt0057435', 'movie', 'The Punch and Judy Man', 'The Punch and Judy Man', 0, 1963.0, None, 96.0, 'Comedy'),
 ('tt0058142', 'movie', 'Girl with Green Eyes', 'Girl with Green Eyes', 0, 1964.0, None, 91.0, 'Drama,Romance'),
 ('tt0058596', 'movie', 'Smokescreen', 'Smokescreen', 0, 1964.0, None, 70.0, 'Crime,Drama,Mystery'),
 ('tt0059106', 'movie', 'Die! Die! My Darling!', 'Fanatic', 0, 1965.0, None, 97.0, 'Horror,Thriller'),
 ('tt0059191', 'tvEpisode', 'For the West', 'For the West', 0, 1965.0, None, 75.0, 'Drama')]

In [ ]:
%sql describe title_basics_raw;

You can see that ```genres``` is multi-valued, and the individual values domain seems to be a fixed set of values, i.e. an ```ENUM.```

You can also infer that a ```title_basics``` has many ```genres``` and a ```genre``` may apply to several ```title_basics.``` $\Rightarrow$ We need an associative entity.

A better model is 

| <img src="multi-valued-erd.jpg"> |
| :---: |
| __Multi-Valued Attributes__ |

It would be relatively easy to write some python code that queries the table, splits the genre into a separate dataframe, creates a dataframe with the associations and write all of the entities to the database.

This approach works for relatively small datasets.

If the dataset is very large, this can be inefficient/expensive. The notebook and database are different programs running in different processes, perhaps on different machines $\Rightarrow$ That is a lot of data movement.

We will also see that advanced databases can parallelize and perform other optimizations on computationally complex queries.

Let's do some work to transform _in the database_ without moving the data.

In [47]:
%%sql

select genres,
            length(genres),
            replace(genres, ',', '') as no_commas,
            length(replace(genres, ',','')) as length_no_commas,
            length(genres) - length(replace(genres, ',','')) + 1 as no_of_genres
    from
        title_basics_raw
order by length(genres) - length(replace(genres, ',','')) + 1 desc
limit 5;

 * mysql+pymysql://root:***@localhost
5 rows affected.

[('Drama,Fantasy,Horror', 20, 'DramaFantasyHorror', 18, 3),
 ('Crime,Drama,Mystery', 19, 'CrimeDramaMystery', 17, 3),
 ('Comedy,Crime,Drama', 18, 'ComedyCrimeDrama', 16, 3),
 ('Horror,Mystery,Thriller', 23, 'HorrorMysteryThriller', 21, 3),
 ('Horror,Mystery,Thriller', 23, 'HorrorMysteryThriller', 21, 3)]

This query "parses" and "splits" the genres.

In [48]:
%%sql

with one as (
    select
        genres,
        if(substr(genres, 1, locate(',', genres)-1)='', null, substr(genres, 1, locate(',', genres)-1)) as g1,
        if(substr(genres, locate(',', genres)+1)='', null, substr(genres, locate(',', genres)+1)) as remainder
    from
        title_basics_raw
),
two as (
    select
        genres, g1,
        if(substr(remainder, 1, locate(',', remainder)-1)='', null, substr(remainder, 1, locate(',', remainder)-1)) as g2,
        if(substr(remainder, locate(',', genres)+1)='', null, substr(remainder, locate(',', remainder)+1)) as g3
    from one
    )
select * from two;

 * mysql+pymysql://root:***@localhost
29058 rows affected.

[('Action,Comedy,Crime', 'Action', 'Comedy', 'Crime'),
 ('Comedy', None, None, 'Comedy'),
 ('Crime,Drama,Thriller', 'Crime', 'Drama', 'Thriller'),
 ('Comedy,Romance', 'Comedy', None, None),
 ('Drama,Romance', 'Drama', None, 'Romance'),
 ('Comedy', None, None, 'Comedy'),
 ('Drama,Romance', 'Drama', None, 'Romance'),
 ('Crime,Drama,Mystery', 'Crime', 'Drama', 'Mystery'),
 ('Horror,Thriller', 'Horror', None, 'Thriller'),
 ('Drama', None, None, 'Drama'),
 ('Drama', None, None, 'Drama'),
 ('Comedy,Crime', 'Comedy', None, None),
 ('Drama,History,War', 'Drama', 'History', 'War'),
 ('Comedy,Crime,Mystery', 'Comedy', 'Crime', 'Mystery'),
 ('Drama', None, None, 'Drama'),
 ('Drama', None, None, 'Drama'),
 ('Drama,Romance', 'Drama', None, 'Romance'),
 ('Crime,Horror,Mystery', 'Crime', 'Horror', 'Mystery'),
 ('Comedy,Romance', 'Comedy', None, None),
 ('Comedy', None, None, 'Comedy'),
 ('Comedy', None, None, 'Comedy'),
 ('Drama', None, None, 'Drama'),
 ('Crime,Drama', 'Crime', None, None),
 ('Drama', None, None, 'Drama'),
 ('Drama,Thriller', 'Drama', None, 'Thriller'),
 ('Crime,Drama', 'Crime', None, None),
 ('Horror,Mystery,Sci-Fi', 'Horror', 'Mystery', 'Sci-Fi'),
 ('Horror,Mystery,Thriller', 'Horror', 'Mystery', 'Thriller'),
 ('Fantasy,Horror', 'Fantasy', None, None),
 ('Drama', None, None, 'Drama'),
 ('Drama', None, None, 'Drama'),
 ('Drama', None, None, 'Drama'),
 ('Drama', None, None, 'Drama'),
 ('Drama,Thriller', 'Drama', None, 'Thriller'),
 ('Drama,Horror,Mystery', 'Drama', 'Horror', 'Mystery'),
 ('Drama,Fantasy,Mystery', 'Drama', 'Fantasy', 'Mystery'),
 ('Comedy,Fantasy,Romance', 'Comedy', 'Fantasy', 'Romance'),
 ('Adventure', None, None, 'Adventure'),
 ('Action,Comedy,Crime', 'Action', 'Comedy', 'Crime'),
 ('Comedy', None, None, 'Comedy'),
 ('Drama,History,War', 'Drama', 'History', 'War'),
 ('Comedy,Drama', 'Comedy', None, None),
 ('Action,Adventure,Comedy', 'Action', 'Adventure', 'Comedy'),
 ('Drama', None, None, 'Drama'),
 ('Action,Drama,History', 'Action', 'Drama', 'History'),
 ('Mystery,Thriller', 'Mystery', None, None),
 ('Adventure,Comedy,Romance', 'Adventure', 'Comedy', 'Romance'),
 ('Crime,Drama,Horror', 'Crime', 'Drama', 'Horror'),
 ('Action,Adventure,Thriller', 'Action', 'Adventure', 'Thriller'),
 ('Crime,Drama,Mystery', 'Crime', 'Drama', 'Mystery'),
 ('Drama', None, None, 'Drama'),
 ('Comedy,Sci-Fi', 'Comedy', None, None),
 ('Biography,Drama,History', 'Biography', 'Drama', 'History'),
 ('Biography', None, None, 'Biography'),
 ('Drama', None, None, 'Drama'),
 ('Drama,History,War', 'Drama', 'History', 'War'),
 ('Drama,War', 'Drama', None, None),
 ('Crime,Drama', 'Crime', None, None),
 ('Comedy', None, None, 'Comedy'),
 ('Drama', None, None, 'Drama'),
 ('Crime,Drama,Thriller', 'Crime', 'Drama', 'Thriller'),
 ('Comedy,Musical,Sci-Fi', 'Comedy', 'Musical', 'Sci-Fi'),
 ('Adventure,Drama,Romance', 'Adventure', 'Drama', 'Romance'),
 ('Drama,Mystery', 'Drama', None, 'Mystery'),
 ('Comedy,Drama', 'Comedy', None, None),
 ('Drama,Romance', 'Drama', None, 'Romance'),
 ('Documentary,Drama', 'Documentary', None, None),
 ('Comedy,Drama,Mystery', 'Comedy', 'Drama', 'Mystery'),
 ('Drama', None, None, 'Drama'),
 ('Crime,Drama,Horror', 'Crime', 'Drama', 'Horror'),
 ('Comedy,Drama', 'Comedy', None, None),
 ('Drama,Romance', 'Drama', None, 'Romance'),
 ('Crime,Drama,Thriller', 'Crime', 'Drama', 'Thriller'),
 ('Horror,Mystery', 'Horror', None, None),
 ('Drama', None, None, 'Drama'),
 ('Crime,Drama,Thriller', 'Crime', 'Drama', 'Thriller'),
 ('Crime,Drama,Mystery', 'Crime', 'Drama', 'Mystery'),
 ('Biography,Drama,Music', 'Biography', 'Drama', 'Music'),
 (None, None, None, None),
 ('Biography,Drama', 'Biography', None, None),
 ('Action,Crime,Drama', 'Action', 'Crime', 'Drama'),
 ('Fantasy,Horror,Mystery', 'Fantasy', 'Horror', 'Mystery'),
 ('Drama,Horror,Mystery', 'Drama', 'Horror', 'Mystery'),
 ('Drama', None, None, 'Drama'),
 ('Comedy', None, None, 'Comedy'),
 ('Documentary,History', 'Documentary', None, None),
 ('Drama,War', 'Drama', None, None),
 ('Biography,Drama,History', 'Biography', 'Drama', 'History'),
 ('Drama', None, None, 'Drama'),
 ('Crime,Drama,Mystery', 'Crime', 'Drama', 'Mystery'),
 ('Biography,Drama', 'Biography', None, None),
 ('Thriller', None, None, 'Thriller'),
 ('Drama', None, None, 'Drama'),
 ('Drama,History,War', 'Drama', 'History', 'War'),
 ('Comedy,Drama,Horror', 'Comedy', 'Drama', 'Horror'),
 ('Drama,Mystery', 'Drama', None, 'Mystery'),
 ('Comedy,Crime,Thriller', 'Comedy', 'Crime', 'Thriller'),
 ('Comedy,Drama,Romance', 'Comedy', 'Drama', 'Romance'),
 ('Drama,Thriller', 'Drama', None, 'Thriller'),
 ('Drama', None, None, 'Drama'),
 ('Action,Thriller', 'Action', None, 'Thriller'),
 ('Comedy,Drama', 'Comedy', None, None),
 ('Drama', None, None, 'Drama'),
 (None, None, None, None),
 ('Crime,Drama,Fantasy', 'Crime', 'Drama', 'Fantasy'),
 ('Drama,History', 'Drama', None, 'History'),
 ('Horror', None, None, 'Horror'),
 ('Crime,Mystery', 'Crime', None, 'Mystery'),
 ('Crime,Drama,Mystery', 'Crime', 'Drama', 'Mystery'),
 (None, None, None, None),
 ('Drama', None, None, 'Drama'),
 ('Thriller', None, None, 'Thriller'),
 ('Horror', None, None, 'Horror'),
 ('Drama', None, None, 'Drama'),
 ('Drama', None, None, 'Drama'),
 ('Drama,History,War', 'Drama', 'History', 'War'),
 ('Crime,Drama,Thriller', 'Crime', 'Drama', 'Thriller'),
 ('Biography,Drama,Romance', 'Biography', 'Drama', 'Romance'),
 ('Biography,Drama,History', 'Biography', 'Drama', 'History'),
 ('Crime,Drama', 'Crime', None, None),
 ('Drama', None, None, 'Drama'),
 ('Action,Adventure,Drama', 'Action', 'Adventure', 'Drama'),
 ('Adventure,Drama,Sci-Fi', 'Adventure', 'Drama', 'Sci-Fi'),
 ('Adventure,Drama,Thriller', 'Adventure', 'Drama', 'Thriller'),
 ('Drama', None, None, 'Drama'),
 ('Drama,Thriller', 'Drama', None, 'Thriller'),
 ('Comedy', None, None, 'Comedy'),
 ('Crime,Thriller', 'Crime', None, 'Thriller'),
 ('Action,Crime,Drama', 'Action', 'Crime', 'Drama'),
 ('Adventure,Animation,Comedy', 'Adventure', 'Animation', 'Comedy'),
 ('Comedy,Musical,Romance', 'Comedy', 'Musical', 'Romance'),
 ('Drama', None, None, 'Drama'),
 ('Crime,Drama,Mystery', 'Crime', 'Drama', 'Mystery'),
 ('Biography,Drama', 'Biography', None, None),
 ('Crime,Drama', 'Crime', None, None),
 (None, None, None, None),
 ('Comedy,Drama', 'Comedy', None, None),
 ('Crime,Drama,Mystery', 'Crime', 'Drama', 'Mystery'),
 ('Drama', None, None, 'Drama'),
 ('Drama', None, None, 'Drama'),
 ('Drama,Horror', 'Drama', None, None),
 ('Comedy,Drama', 'Comedy', None, None),
 ('Comedy', None, None, 'Comedy'),
 ('Action,Drama,History', 'Action', 'Drama', 'History'),
 ('Biography,Drama,History', 'Biography', 'Drama', 'History'),
 ('Comedy,Crime,Drama', 'Comedy', 'Crime', 'Drama'),
 ('Drama', None, None, 'Drama'),
 ('Comedy,Drama,Romance', 'Comedy', 'Drama', 'Romance'),
 ('Comedy,Drama', 'Comedy', None, None),
 ('Action,Adventure,Romance', 'Action', 'Adventure', 'Romance'),
 ('Action,Crime,Drama', 'Action', 'Crime', 'Drama'),
 ('Adventure,Horror,Sci-Fi', 'Adventure', 'Horror', 'Sci-Fi'),
 ('Thriller', None, None, 'Thriller'),
 ('Horror', None, None, 'Horror'),
 ('Drama,Music', 'Drama', None, None),
 ('Comedy,Crime', 'Comedy', None, None),
 ('Drama,Music', 'Drama', None, None),
 ('Adventure,Drama,History', 'Adventure', 'Drama', 'History'),
 ('Crime,Drama,Mystery', 'Crime', 'Drama', 'Mystery'),
 ('Drama,Musical', 'Drama', None, 'Musical'),
 ('Comedy', None, None, 'Comedy'),
 ('Drama,History', 'Drama', None, 'History'),
 ('Drama', None, None, 'Drama'),
 ('Biography,Drama', 'Biography', None, None),
 (None, None, None, None),
 ('Drama', None, None, 'Drama'),
 ('Adventure,Crime,Drama', 'Adventure', 'Crime', 'Drama'),
 ('Comedy,Romance', 'Comedy', None, None),
 ('Adventure,Comedy,Fantasy', 'Adventure', 'Comedy', 'Fantasy'),
 ('Comedy', None, None, 'Comedy'),
 ('Drama', None, None, 'Drama'),
 ('Action,Adventure,Thriller', 'Action', 'Adventure', 'Thriller'),
 ('Drama,Romance', 'Drama', None, 'Romance'),
 ('Adventure,Comedy,Crime', 'Adventure', 'Comedy', 'Crime'),
 ('Crime,Mystery', 'Crime', None, 'Mystery'),
 ('Biography,Drama,Romance', 'Biography', 'Drama', 'Romance'),
 ('Comedy,Drama', 'Comedy', None, None),
 ('Drama', None, None, 'Drama'),
 ('Adventure,Comedy,Mystery', 'Adventure', 'Comedy', 'Mystery'),
 ('Drama,Music,Thriller', 'Drama', 'Music', 'Thriller'),
 ('Drama', None, None, 'Drama'),
 ('Biography,Drama', 'Biography', None, None),
 ('Crime,Drama,Horror', 'Crime', 'Drama', 'Horror'),
 ('Crime,Drama,Mystery', 'Crime', 'Drama', 'Mystery'),
 ('Adventure,Biography,Comedy', 'Adventure', 'Biography', 'Comedy'),
 ('Drama,Romance', 'Drama', None, 'Romance'),
 ('Adventure,Drama,Romance', 'Adventure', 'Drama', 'Romance'),
 ('Drama', None, None, 'Drama'),
 ('Drama', None, None, 'Drama'),
 ('Crime,Drama,Romance', 'Crime', 'Drama', 'Romance'),
 ('Comedy,Drama,War', 'Comedy', 'Drama', 'War'),
 ('Drama', None, None, 'Drama'),
 ('Drama,Romance', 'Drama', None, 'Romance'),
 ('Comedy', None, None, 'Comedy'),
 ('Comedy', None, None, 'Comedy'),
 ('Comedy,Talk-Show', 'Comedy', None, 'Talk-Show'),
 ('Drama,Music', 'Drama', None, None),
 ('Biography,Drama', 'Biography', None, None),
 ('Comedy', None, None, 'Comedy'),
 ('Drama', None, None, 'Drama'),
 ('Comedy,Crime,Romance', 'Comedy', 'Crime', 'Romance'),
 ('Crime,Drama,Mystery', 'Crime', 'Drama', 'Mystery'),
 ('Comedy', None, None, 'Comedy'),
 ('Action,Drama,Fantasy', 'Action', 'Drama', 'Fantasy'),
 ('Action,Biography,Drama', 'Action', 'Biography', 'Drama'),
 ('Biography,Drama,Music', 'Biography', 'Drama', 'Music'),
 ('Drama,History', 'Drama', None, 'History'),
 ('Comedy', None, None, 'Comedy'),
 ('Comedy', None, None, 'Comedy'),
 ('Drama,Horror,Mystery', 'Drama', 'Horror', 'Mystery'),
 ('Adventure', None, None, 'Adventure'),
 ('Drama', None, None, 'Drama'),
 ('Crime,Drama,Thriller', 'Crime', 'Drama', 'Thriller'),
 ('Adventure,Drama,Family', 'Adventure', 'Drama', 'Family'),
 ('Drama', None, None, 'Drama'),
 ('Drama', None, None, 'Drama'),
 ('Drama,Sci-Fi', 'Drama', None, None),
 ('Mystery,Thriller', 'Mystery', None, None),
 ('Drama,Romance,War', 'Drama', 'Romance', 'War'),
 ('Drama,Thriller', 'Drama', None, 'Thriller'),
 ('Drama,Romance', 'Drama', None, 'Romance'),
 ('Drama,Romance', 'Drama', None, 'Romance'),
 ('Comedy', None, None, 'Comedy'),
 ('Drama,History', 'Drama', None, 'History'),
 ('Comedy', None, None, 'Comedy'),
 ('Crime,Drama', 'Crime', None, None),
 ('Drama,Family,Romance', 'Drama', 'Family', 'Romance'),
 ('Comedy', None, None, 'Comedy'),
 ('Adventure', None, None, 'Adventure'),
 ('Drama', None, None, 'Drama'),
 ('Drama,Thriller', 'Drama', None, 'Thriller'),
 ('Drama', None, None, 'Drama'),
 ('Drama,Sci-Fi,Thriller', 'Drama', 'Sci-Fi', 'Thriller'),
 ('Drama,Mystery,Romance', 'Drama', 'Mystery', 'Romance'),
 ('Crime,Drama,History', 'Crime', 'Drama', 'History'),
 ('Drama,Romance,War', 'Drama', 'Romance', 'War'),
 ('Drama', None, None, 'Drama'),
 ('Comedy', None, None, 'Comedy'),
 ('Drama,Thriller', 'Drama', None, 'Thriller'),
 ('Drama', None, None, 'Drama'),
 ('Comedy,Crime,Drama', 'Comedy', 'Crime', 'Drama'),
 ('Drama', None, None, 'Drama'),
 ('Drama', None, None, 'Drama'),
 ('Crime', None, None, 'Crime'),
 ('Crime,Drama,Horror', 'Crime', 'Drama', 'Horror'),
 ('Drama,Music', 'Drama', None, None),
 ('Adventure,Fantasy,Mystery', 'Adventure', 'Fantasy', 'Mystery'),
 ('Drama', None, None, 'Drama'),
 ('Comedy', None, None, 'Comedy'),
 ('Comedy,Crime,Drama', 'Comedy', 'Crime', 'Drama'),
 ('Drama,Musical,Mystery', 'Drama', 'Musical', 'Mystery'),
 ('Adventure,Drama', 'Adventure', None, None),
 ('Biography,Drama,History', 'Biography', 'Drama', 'History'),
 ('Drama', None, None, 'Drama'),
 ('Action,Adventure,Fantasy', 'Action', 'Adventure', 'Fantasy'),
 ('Action,Adventure,Comedy', 'Action', 'Adventure', 'Comedy'),
 ('Comedy', None, None, 'Comedy'),
 ('Drama', None, None, 'Drama'),
 ('Drama', None, None, 'Drama'),
 ('Crime,Horror,Mystery', 'Crime', 'Horror', 'Mystery'),
 ('Drama', None, None, 'Drama'),
 ('Comedy,Drama,Romance', 'Comedy', 'Drama', 'Romance'),
 ('Comedy,Drama', 'Comedy', None, None),
 ('Action,Drama,Fantasy', 'Action', 'Drama', 'Fantasy'),
 ('Drama', None, None, 'Drama'),
 ('Comedy,Family,Fantasy', 'Comedy', 'Family', 'Fantasy'),
 ('Action,Adventure,Comedy', 'Action', 'Adventure', 'Comedy'),
 ('Crime,Drama,Fantasy', 'Crime', 'Drama', 'Fantasy'),
 ('Comedy', None, None, 'Comedy'),
 ('Comedy,Drama', 'Comedy', None, None),
 ('Comedy', None, None, 'Comedy'),
 ('Comedy,Drama,Music', 'Comedy', 'Drama', 'Music'),
 ('Crime,Drama,Mystery', 'Crime', 'Drama', 'Mystery'),
 ('Crime,Drama', 'Crime', None, None),
 ('Thriller', None, None, 'Thriller'),
 ('Drama', None, None, 'Drama'),
 ('Thriller', None, None, 'Thriller'),
 (None, None, None, None),
 ('Drama,Romance', 'Drama', None, 'Romance'),
 ('Drama,Music,Romance', 'Drama', 'Music', 'Romance'),
 ('Action,Drama,Thriller', 'Action', 'Drama', 'Thriller'),
 ('Drama', None, None, 'Drama'),
 ('Drama', None, None, 'Drama'),
 ('Horror,Mystery,Sci-Fi', 'Horror', 'Mystery', 'Sci-Fi'),
 ('Biography,Drama,Romance', 'Biography', 'Drama', 'Romance'),
 (None, None, None, None),
 ('Drama', None, None, 'Drama'),
 ('Adventure,Comedy,Drama', 'Adventure', 'Comedy', 'Drama'),
 ('Drama,Family', 'Drama', None, None),
 ('Family,Fantasy,Musical', 'Family', 'Fantasy', 'Musical'),
 ('Drama,Thriller', 'Drama', None, 'Thriller'),
 ('Drama', None, None, 'Drama'),
 ('Crime,Drama,Mystery', 'Crime', 'Drama', 'Mystery'),
 ('Comedy,Drama', 'Comedy', None, None),
 ('Drama,Romance', 'Drama', None, 'Romance'),
 ('Adventure,Drama,Family', 'Adventure', 'Drama', 'Family'),
 ('Comedy', None, None, 'Comedy'),
 ('Biography,Drama', 'Biography', None, None),
 ('Crime,Drama', 'Crime', None, None),
 ('Comedy', None, None, 'Comedy'),
 ('Drama', None, None, 'Drama'),
 ('Drama,Thriller', 'Drama', None, 'Thriller'),
 ('Crime,Drama,Mystery', 'Crime', 'Drama', 'Mystery'),
 ('Drama', None, None, 'Drama'),
 ('Comedy,History', 'Comedy', None, None),
 ('Action,Adventure,Drama', 'Action', 'Adventure', 'Drama'),
 ('Drama,Thriller', 'Drama', None, 'Thriller'),
 ('Comedy', None, None, 'Comedy'),
 ('Drama', None, None, 'Drama'),
 ('Biography,Drama', 'Biography', None, None),
 ('Action,Adventure,Drama', 'Action', 'Adventure', 'Drama'),
 ('Mystery,Thriller', 'Mystery', None, None),
 ('Crime,Drama,Mystery', 'Crime', 'Drama', 'Mystery'),
 ('Crime,Drama,Mystery', 'Crime', 'Drama', 'Mystery'),
 ('Drama', None, None, 'Drama'),
 ('Drama', None, None, 'Drama'),
 ('Drama', None, None, 'Drama'),
 ('Thriller', None, None, 'Thriller'),
 ('Thriller', None, None, 'Thriller'),
 ('Drama,Thriller', 'Drama', None, 'Thriller'),
 ('Drama', None, None, 'Drama'),
 ('Crime,Drama,Music', 'Crime', 'Drama', 'Music'),
 ('Drama,Romance', 'Drama', None, 'Romance'),
 ('Drama,Romance', 'Drama', None, 'Romance'),
 ('Drama,War', 'Drama', None, None),
 ('Drama', None, None, 'Drama'),
 ('Drama,Thriller', 'Drama', None, 'Thriller'),
 ('Comedy,War', 'Comedy', None, None),
 ('Adventure', None, None, 'Adventure'),
 ('Drama,Sci-Fi', 'Drama', None, None),
 ('Drama', None, None, 'Drama'),
 ('Drama,Thriller', 'Drama', None, 'Thriller'),
 ('Comedy,Family', 'Comedy', None, None),
 ('Comedy,Sci-Fi', 'Comedy', None, None),
 ('Adventure,Comedy,Fantasy', 'Adventure', 'Comedy', 'Fantasy'),
 ('Drama', None, None, 'Drama'),
 ('Crime,Drama,Mystery', 'Crime', 'Drama', 'Mystery'),
 ('Action,Comedy', 'Action', None, None),
 ('Crime,Drama,Mystery', 'Crime', 'Drama', 'Mystery'),
 ('Crime,Drama', 'Crime', None, None),
 ('Drama,Thriller', 'Drama', None, 'Thriller'),
 ('Crime,Drama,Mystery', 'Crime', 'Drama', 'Mystery'),
 ('Comedy,Crime,Drama', 'Comedy', 'Crime', 'Drama'),
 ('Crime,Drama,Mystery', 'Crime', 'Drama', 'Mystery'),
 ('Drama,History,Romance', 'Drama', 'History', 'Romance'),
 ('Drama,History,Thriller', 'Drama', 'History', 'Thriller'),
 ('Biography', None, None, 'Biography'),
 ('Drama', None, None, 'Drama'),
 ('Comedy,Fantasy', 'Comedy', None, None),
 ('Action,Adventure', 'Action', None, 'Adventure'),
 ('Action,Thriller', 'Action', None, 'Thriller'),
 ('Comedy', None, None, 'Comedy'),
 ('Adventure', None, None, 'Adventure'),
 ('Drama,Mystery', 'Drama', None, 'Mystery'),
 ('Comedy,Family,Fantasy', 'Comedy', 'Family', 'Fantasy'),
 ('Drama', None, None, 'Drama'),
 ('Drama', None, None, 'Drama'),
 ('Comedy,Crime', 'Comedy', None, None),
 ('Biography,Drama,War', 'Biography', 'Drama', None),
 ('Comedy,Drama,Romance', 'Comedy', 'Drama', 'Romance'),
 ('Drama', None, None, 'Drama'),
 ('Action,Fantasy,Horror', 'Action', 'Fantasy', 'Horror'),
 ('Comedy,Short', 'Comedy', None, None),
 ('Biography,Comedy,Drama', 'Biography', 'Comedy', 'Drama'),
 ('Crime,Drama,Mystery', 'Crime', 'Drama', 'Mystery'),
 ('Crime,Drama,Mystery', 'Crime', 'Drama', 'Mystery'),
 ('Comedy', None, None, 'Comedy'),
 ('Drama,Fantasy,Horror', 'Drama', 'Fantasy', 'Horror'),
 ('Drama', None, None, 'Drama'),
 (None, None, None, None),
 ('Drama,Fantasy,Horror', 'Drama', 'Fantasy', 'Horror'),
 ('Comedy', None, None, 'Comedy'),
 ('Drama,War', 'Drama', None, None),
 ('Adventure,Biography,Drama', 'Adventure', 'Biography', 'Drama'),
 ('Horror,Romance', 'Horror', None, None),
 ('Drama', None, None, 'Drama'),
 ('Drama,Mystery,Thriller', 'Drama', 'Mystery', 'Thriller'),
 ('Drama,Thriller', 'Drama', None, 'Thriller'),
 ('Drama,Romance', 'Drama', None, 'Romance'),
 ('Crime', None, None, 'Crime'),
 ('Comedy', None, None, 'Comedy'),
 ('Drama', None, None, 'Drama'),
 ('Biography,Drama', 'Biography', None, None),
 ('Drama,War', 'Drama', None, None),
 ('Drama,Thriller', 'Drama', None, 'Thriller'),
 ('Crime,Drama', 'Crime', None, None),
 ('Comedy,Drama', 'Comedy', None, None),
 ('Drama,Romance', 'Drama', None, 'Romance'),
 ('Drama,Romance,War', 'Drama', 'Romance', 'War'),
 ('Adventure,Drama,History', 'Adventure', 'Drama', 'History'),
 ('Crime,Drama,Mystery', 'Crime', 'Drama', 'Mystery'),
 ('Adventure,Drama,Thriller', 'Adventure', 'Drama', 'Thriller'),
 ('Crime,Drama,Fantasy', 'Crime', 'Drama', 'Fantasy'),
 ('Crime,Drama', 'Crime', None, None),
 ('Drama,Music,Mystery', 'Drama', 'Music', 'Mystery'),
 ('Action,Adventure,Animation', 'Action', 'Adventure', 'Animation'),
 ('Biography,Crime,Drama', 'Biography', 'Crime', 'Drama'),
 ('Drama', None, None, 'Drama'),
 ('Action,Adventure,Crime', 'Action', 'Adventure', 'Crime'),
 ('Adventure', None, None, 'Adventure'),
 ('Action,Drama,Thriller', 'Action', 'Drama', 'Thriller'),
 ('Drama', None, None, 'Drama'),
 ('Drama,History', 'Drama', None, 'History'),
 ('Animation,Comedy,Crime', 'Animation', 'Comedy', 'Crime'),
 ('Comedy', None, None, 'Comedy'),
 ('Comedy', None, None, 'Comedy'),
 ('Drama,Music', 'Drama', None, None),
 ('Comedy', None, None, 'Comedy'),
 ('Comedy,Crime,Drama', 'Comedy', 'Crime', 'Drama'),
 ('Comedy,Crime,Drama', 'Comedy', 'Crime', 'Drama'),
 ('Sci-Fi', None, None, 'Sci-Fi'),
 ('Action,Drama', 'Action', None, None),
 ('Drama', None, None, 'Drama'),
 ('Drama,History,Romance', 'Drama', 'History', 'Romance'),
 ('Drama,Thriller', 'Drama', None, 'Thriller'),
 ('Drama', None, None, 'Drama'),
 ('Drama', None, None, 'Drama'),
 ('Drama,Romance', 'Drama', None, 'Romance'),
 ('Drama', None, None, 'Drama'),
 ('Action,Adventure,Comedy', 'Action', 'Adventure', 'Comedy'),
 ('Drama', None, None, 'Drama'),
 ('Comedy,Romance', 'Comedy', None, None),
 ('Drama', None, None, 'Drama'),
 ('Comedy,Drama,Fantasy', 'Comedy', 'Drama', 'Fantasy'),
 ('Drama', None, None, 'Drama'),
 ('Comedy,Romance', 'Comedy', None, None),
 ('Crime,Drama,Mystery', 'Crime', 'Drama', 'Mystery'),
 ('Crime,Drama,Mystery', 'Crime', 'Drama', 'Mystery'),
 ('Comedy,Crime,Drama', 'Comedy', 'Crime', 'Drama'),
 ('Biography,Drama', 'Biography', None, None),
 ('Action,Adventure,Drama', 'Action', 'Adventure', 'Drama'),
 ('Action,Comedy,Sci-Fi', 'Action', 'Comedy', 'Sci-Fi'),
 ('Comedy,Crime,Drama', 'Comedy', 'Crime', 'Drama'),
 ('Drama', None, None, 'Drama'),
 ('Adventure,History', 'Adventure', None, None),
 ('Comedy,Drama', 'Comedy', None, None),
 ('Comedy,Drama', 'Comedy', None, None),

With a little bit more work, I can
- Get the unique values for g1, g2, g3.
- Make a table with the unique values and create an auto-increment primary key.
- Build the associative entity link the genres with the titles.
- Delete the genres column from titles.

This is an example of the __fun data engineering__ that students will perform on the non-programming homeworks/project.

Have fun.

| <img src="fun.jpg" width-=500px> |
| :---: |
| __Fun__ |

# Index Example

[Lahman's Baseball Database](https://www.kaggle.com/datasets/freshrenzo/lahmanbaseballdatabase) is an interesting dataset for data engineering and analysis.

In [ ]:
people_df = pandas.read_csv("./people.csv")

In [ ]:
batting_df = pandas.read_csv("./batting.csv")

In [ ]:
appearances_df = pandas.read_csv("./appearances.csv")

In [ ]:
%sql drop table if exists people;
%sql drop table if exists batting;
%sql drop table if exists appearances;

In [ ]:
%%sql

drop index  batting_playerID_index on batting;

drop index  people_player_ID_index on people;

In [ ]:
people_df.to_sql(
    "people",
    schema="f2025_w4111_examples",
    con=engine,
    index=False,
    if_exists="replace"
)

In [ ]:
batting_df.to_sql(
    "batting",
    schema="f2025_w4111_examples",
    con=engine,
    index=False,
    if_exists="replace"
)

In [ ]:
appearances_df.to_sql(
    "appearances",
    schema="f2025_w4111_examples",
    con=engine,
    index=False,
    if_exists="replace"
)

In [ ]:
from time import time

start_time = time()

for i in range(0, 1):
    result = %sql with one as (select playerID, \
                        nameLast, \
                        nameFirst, \
                        sum(H)   as H, \
                        sum(AB)  as AB, \
                        sum(BB)  as BB, \
                        sum(HR)  as HR, \
                        sum(RBI) as RBI, \
                        ( \
                            (sum(H) + sum(BB)) / \
                            (if(sum(AB) + sum(BB) = 0, NULL, sum(AB) + sum(BB))) \
                            ) as obp \
                 from people \
                          join batting using (playerID) \
                 group by playerID, nameLast, nameFirst) \
        select * from one  where playerID='willite01' and AB > 1000
    
end_time = time()

elapsed_time = (end_time - start_time)

print ("Elapsed time = ", elapsed_time)

In [ ]:
from time import time

start_time = time()

for i in range(0, 1):
    result = %sql select * from people where nameLast="Williams"
    
end_time = time()

elapsed_time = (end_time - start_time)

print ("Elapsed time = ", elapsed_time)

In [ ]:
%%sql

alter table batting
    modify playerID varchar(16) null;

alter table people
    modify playerID varchar(16) null;

alter table people
    modify nameLast varchar(128) null;

create index batting_playerID_index
    on batting (playerID);

create index people_player_ID_index
    on people(playerID);

In [ ]:
from time import time

start_time = time()

for i in range(0, 1):
    result = %sql select * from people where nameLast="Williams"
    
end_time = time()

elapsed_time = (end_time - start_time)

print ("Elapsed time = ", elapsed_time)

In [ ]:
from time import time

start_time = time()

for i in range(0, 1):
    result = %sql with one as (select playerID, \
                        nameLast, \
                        nameFirst, \
                        sum(H)   as H, \
                        sum(AB)  as AB, \
                        sum(BB)  as BB, \
                        sum(HR)  as HR, \
                        sum(RBI) as RBI, \
                        ( \
                            (sum(H) + sum(BB)) / \
                            (if(sum(AB) + sum(BB) = 0, NULL, sum(AB) + sum(BB))) \
                            ) as obp \
                 from people \
                          join batting using (playerID) \
                 group by playerID, nameLast, nameFirst) \
        select * from one  where playerID='willite01';
    
end_time = time()

elapsed_time2 = (end_time - start_time)

print ("Elapsed time = ", elapsed_time)

# Worked Example: Student, Faculty, Person

## Base Tables

In [ ]:
%%sql 

use f2025_w4111_examples;

drop table if exists Person;

create table Person
(
    UNI             varchar(12)  not null,
    last_name       varchar(64)  not null,
    first_name      varchar(64)  not null,
    preferred_email varchar(128) not null,
    /*
     Since I am putting an index on default email, it must be stored.
     Since the UNI is unique, I do not need to worry about a unique constraint.
     */
    default_email   varchar(128) as (concat(UNI, '@columbia.edu')) stored,
    constraint Person_pk
        primary key (UNI),
    constraint Person_pk_2
        unique (preferred_email)
);

create index Person_default_email_index
    on Person (default_email);

In [ ]:
%%sql

drop table if exists Faculty;

create table Faculty
(
    UNI        varchar(12)                                                                                                          not null,
    department varchar(4)                                                                                                           not null,
    title      enum ('Professor', 'Associate Professor', 'Assistant Professor', 'Adjunct Professor', 'Lecturer', 'Senior Lecturer') not null,
    salary     double                                                                                                               not null,
    constraint Faculty_pk
        primary key (UNI),
    constraint Faculty_Person_UNI_fk
        foreign key (UNI) references Person (UNI)
);

In [ ]:
%%sql

drop table if exists Student;

create table Student
(
    UNI             varchar(12)                 not null,
    graduation_year varchar(4)                  not null,
    major           varchar(32)                 not null,
    constraint Student_pk
        primary key (UNI),
    constraint Student_Person_UNI_fk
        foreign key (UNI) references Person (UNI)
);

## Views

In [ ]:
%%sql

create or replace view FacultyPublic as
    select
        Person.*,
        department, title
    from
        Person JOIN Faculty using(UNI);

create or replace view StudentPublic as
    select
        *
    from
        Person NATURAL JOIN Student;

## Computing UNI

In [ ]:
%%sql

drop function if exists compute_next_uni;


CREATE FUNCTION compute_next_uni(first_name varchar(64), last_name varchar(64))
    RETURNS varchar(12)
    DETERMINISTIC
BEGIN
    -- Declare local variables if needed
    DECLARE result varchar(12);
    declare first_initial char(1);
    declare last_initial char(1);
    declare uni_prefix char(3);
    declare prefix_count int;

    set first_initial = lower(substr(first_name, 1, 1));
    set last_initial = lower(substr(last_name, 1, 1));
    set uni_prefix = concat(first_initial, last_initial, '%');

    set prefix_count = (select count(*) from person where uni like uni_prefix);

    set result = concat(first_initial, last_initial, prefix_count + 1);

    RETURN result;
END;

## Procedures

In [ ]:
%%sql

drop procedure if exists create_faculty;

CREATE DEFINER=`root`@`localhost` PROCEDURE create_faculty (
    IN new_first_name varchar(64),
    IN new_last_name varchar(64),
    IN new_preferred_email varchar(128),
    in new_title enum('Professor', 'Associate Professor', 'Assistant Professor', 'Adjunct Professor', 'Lecturer', 'Senior Lecturer'),
    in new_salary double,
    in new_department varchar(4),
    OUT new_uni varchar(12)
)
SQL SECURITY DEFINER
BEGIN
    set new_uni = compute_next_uni(new_first_name, new_last_name);
    insert into Person(UNI, first_name, last_name, preferred_email)
        value(new_uni, new_first_name, new_last_name, new_preferred_email);
    insert into Faculty(UNI,department, title, salary)
        value(new_uni, new_department, new_title, new_salary);

END;

drop procedure if exists create_student;

CREATE DEFINER=`root`@`localhost` PROCEDURE create_student (
    IN new_first_name varchar(64),
    IN new_last_name varchar(64),
    IN new_preferred_email varchar(128),
    IN new_graduation_year YEAR,
    IN new_major varchar(32),
    OUT new_uni varchar(12)
)
SQL SECURITY DEFINER
BEGIN
    set new_uni = compute_next_uni(new_first_name, new_last_name);
    insert into Person(UNI, first_name, last_name, preferred_email)
        value(new_uni, new_first_name, new_last_name, new_preferred_email);
    insert into Student(UNI, graduation_year, major)
        value(new_uni, new_graduation_year, new_major);

END;

## Some Constraints

Let's put some constraints:
1. ```preferred_email``` must contain ```@```.
2. ```salary``` must be greater than ```0```.

In [ ]:
%%sql

alter table Person
    add constraint check_preffered_email
        check (LOCATE('@', Person.preferred_email) > 0);

alter table Faculty
    add constraint check_salary
        check (salary >= 0);

## Some Security

General users should not be able to mess around with ```Faculty``` and see the ```salary```.

In [ ]:
%%sql

create user general_user
    identified by 'dbuserdbuser';

In [ ]:
%sql mysql+pymysql://general_user:dbuserdbuser@localhost --alias general_user_connection

In [ ]:
%sql general_user@localhost select * from f2025_w4111_examples.Faculty;

The default is that a user has not GRANTs or priveliges.

Let's allow the user to query ```Person```.

In [ ]:
%sql root@localhost

%sql GRANT SELECT ON f2025_w4111_examples.Person TO 'general_user' @'%'

In [ ]:
%sql general_user@localhost select * from f2025_w4111_examples.Person

In [ ]:
#
# Let's add some additional grants.
#
%sql root@localhost GRANT SELECT ON f2025_w4111_examples.FacultyPublic TO 'general_user' @'%';
%sql root@localhost GRANT SELECT ON f2025_w4111_examples.StudentPublic TO 'general_user' @'%';

In [ ]:
%sql general_user@localhost select * from f2025_w4111_examples.facultypublic;

In [ ]:
%sql general_user@localhost select * from f2025_w4111_examples.studentpublic;

I can allow ```general_user``` to create ```faculty``` and ```students``` without understanding the physical implementation. That is, ```general_user``` does not:
- Need ```insert``` priveleges.
- Does not need to understand that he/she has to ```insert``` into two tables.

In [ ]:
%%sql root@localhost

GRANT EXECUTE
    ON PROCEDURE f2025_w4111_examples.create_faculty
    TO 'general_user'@'%';

In [ ]:
%%sql general_user@localhost

use f2025_w4111_examples;

call create_faculty(
        "Douglas", "Fairbanks",
        "dfairbanks@cs.columbia.edu",
        "Professor",
        0,
        "COMS",
        @new_Uni
     );

In [ ]:
%sql general_user@localhost select * from Person

In [ ]:
%sql general_user@localhost select * from FacultyPublic

# Windows Functions

In [ ]:
%%sql

SELECT    country,    YEAR(orderDate) AS year,    ROUND(SUM(priceEach * quantityOrdered), 2) AS annual_revenue,    ROUND(        (SUM(priceEach * quantityOrdered) -        LAG(SUM(priceEach * quantityOrdered)) OVER (PARTITION BY country ORDER BY YEAR(orderDate))) /        LAG(SUM(priceEach * quantityOrdered)) OVER (PARTITION BY country ORDER BY YEAR(orderDate)) * 100, 2    ) AS yoy_growth_percentageFROM    customers    JOIN orders ON customers.customerNumber = orders.customerNumber    JOIN orderdetails ON orders.orderNumber = orderdetails.orderNumberGROUP BY    country, yearORDER BY    country, year;